/**
 * This is an autogenerated libdef stub for:
 *
 *   'glamor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'glamor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'glamor/aphrodite' {
  declare module.exports: any;
}

declare module 'glamor/jsxstyle' {
  declare module.exports: any;
}

declare module 'glamor/lib/aphrodite' {
  declare module.exports: any;
}

declare module 'glamor/lib/autoprefix' {
  declare module.exports: any;
}

declare module 'glamor/lib/clean' {
  declare module.exports: any;
}

declare module 'glamor/lib/color' {
  declare module.exports: any;
}

declare module 'glamor/lib/cssnext' {
  declare module.exports: any;
}

declare module 'glamor/lib/CSSPropertyOperations' {
  declare module.exports: any;
}

declare module 'glamor/lib/extract' {
  declare module.exports: any;
}

declare module 'glamor/lib/filters' {
  declare module.exports: any;
}

declare module 'glamor/lib/glam' {
  declare module.exports: any;
}

declare module 'glamor/lib/hash' {
  declare module.exports: (css: string) => number;
}

declare module 'glamor/lib/index' {
  declare module.exports: any;
}

declare module 'glamor/lib/jsxstyle' {
  declare module.exports: any;
}

declare module 'glamor/lib/lint' {
  declare module.exports: any;
}

declare module 'glamor/lib/ous' {
  declare module.exports: any;
}

declare module 'glamor/lib/plugins' {
  declare module.exports: any;
}

declare module 'glamor/lib/react' {
  declare module.exports: any;
}

declare module 'glamor/lib/reset' {
  declare module.exports: any;
}

declare module 'glamor/lib/server' {
  declare module.exports: any;
}

declare module 'glamor/lib/sheet' {
  declare module.exports: any;
}

declare module 'glamor/lib/utils' {
  declare module.exports: any;
}

declare module 'glamor/ous' {
  declare module.exports: any;
}

declare module 'glamor/react' {
  declare module.exports: any;
}

declare module 'glamor/reset' {
  declare module.exports: any;
}

declare module 'glamor/server' {
  declare module.exports: any;
}

declare module 'glamor/umd/index' {
  declare module.exports: any;
}

declare module 'glamor/umd/index.min' {
  declare module.exports: any;
}

declare module 'glamor/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'glamor/aphrodite.js' {
  declare module.exports: $Exports<'glamor/aphrodite'>;
}
declare module 'glamor/jsxstyle.js' {
  declare module.exports: $Exports<'glamor/jsxstyle'>;
}
declare module 'glamor/lib/aphrodite.js' {
  declare module.exports: $Exports<'glamor/lib/aphrodite'>;
}
declare module 'glamor/lib/autoprefix.js' {
  declare module.exports: $Exports<'glamor/lib/autoprefix'>;
}
declare module 'glamor/lib/clean.js' {
  declare module.exports: $Exports<'glamor/lib/clean'>;
}
declare module 'glamor/lib/color.js' {
  declare module.exports: $Exports<'glamor/lib/color'>;
}
declare module 'glamor/lib/cssnext.js' {
  declare module.exports: $Exports<'glamor/lib/cssnext'>;
}
declare module 'glamor/lib/CSSPropertyOperations.js' {
  declare module.exports: $Exports<'glamor/lib/CSSPropertyOperations'>;
}
declare module 'glamor/lib/extract.js' {
  declare module.exports: $Exports<'glamor/lib/extract'>;
}
declare module 'glamor/lib/filters.js' {
  declare module.exports: $Exports<'glamor/lib/filters'>;
}
declare module 'glamor/lib/glam.js' {
  declare module.exports: $Exports<'glamor/lib/glam'>;
}
declare module 'glamor/lib/hash.js' {
  declare module.exports: $Exports<'glamor/lib/hash'>;
}
declare module 'glamor/lib/index.js' {
  declare module.exports: $Exports<'glamor/lib/index'>;
}
declare module 'glamor/lib/jsxstyle.js' {
  declare module.exports: $Exports<'glamor/lib/jsxstyle'>;
}
declare module 'glamor/lib/lint.js' {
  declare module.exports: $Exports<'glamor/lib/lint'>;
}
declare module 'glamor/lib/ous.js' {
  declare module.exports: $Exports<'glamor/lib/ous'>;
}
declare module 'glamor/lib/plugins.js' {
  declare module.exports: $Exports<'glamor/lib/plugins'>;
}
declare module 'glamor/lib/react.js' {
  declare module.exports: $Exports<'glamor/lib/react'>;
}
declare module 'glamor/lib/reset.js' {
  declare module.exports: $Exports<'glamor/lib/reset'>;
}
declare module 'glamor/lib/server.js' {
  declare module.exports: $Exports<'glamor/lib/server'>;
}
declare module 'glamor/lib/sheet.js' {
  declare module.exports: $Exports<'glamor/lib/sheet'>;
}
declare module 'glamor/lib/utils.js' {
  declare module.exports: $Exports<'glamor/lib/utils'>;
}
declare module 'glamor/ous.js' {
  declare module.exports: $Exports<'glamor/ous'>;
}
declare module 'glamor/react.js' {
  declare module.exports: $Exports<'glamor/react'>;
}
declare module 'glamor/reset.js' {
  declare module.exports: $Exports<'glamor/reset'>;
}
declare module 'glamor/server.js' {
  declare module.exports: $Exports<'glamor/server'>;
}
declare module 'glamor/umd/index.js' {
  declare module.exports: $Exports<'glamor/umd/index'>;
}
declare module 'glamor/umd/index.min.js' {
  declare module.exports: $Exports<'glamor/umd/index.min'>;
}
declare module 'glamor/utils.js' {
  declare module.exports: $Exports<'glamor/utils'>;
}
