workflow:
  - install
  - sail:parallel:
    - flow
    - lint
    - build
    - test-web
tasks:
  install:
    image: node:10
    command:
      - yarn
    env:
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
  test-web:
    image: node:10
    cwd: ./packages/styled-components/
    command:
      - yarn
    args:
      - test:web
  flow:
    image: node:10
    command:
      - yarn
    args:
      - flow
  lint:
    image: node:10
    command:
      - yarn
    args:
      - lint
  build:
    image: node:10
    cwd: ./packages/styled-components/
    command:
      - yarn
    args:
      - build
