// <reference path="../react/react.d.ts" />

declare module 'styled-components' {
    import * as React from "react";
    import { StatelessComponent } from "react";

    interface StyledInterface {
        <T>(component: T): (values: TemplateStringsArray) => T,

        h1<P>(values: TemplateStringsArray): StatelessComponent<P>,
        a<P>(values: TemplateStringsArray): StatelessComponent<P>,
        abbr<P>(values: TemplateStringsArray): StatelessComponent<P>,
        address<P>(values: TemplateStringsArray): StatelessComponent<P>,
        area<P>(values: TemplateStringsArray): StatelessComponent<P>,
        article<P>(values: TemplateStringsArray): StatelessComponent<P>,
        aside<P>(values: TemplateStringsArray): StatelessComponent<P>,
        audio<P>(values: TemplateStringsArray): StatelessComponent<P>,
        b<P>(values: TemplateStringsArray): StatelessComponent<P>,
        base<P>(values: TemplateStringsArray): StatelessComponent<P>,
        bdi<P>(values: TemplateStringsArray): StatelessComponent<P>,
        bdo<P>(values: TemplateStringsArray): StatelessComponent<P>,
        big<P>(values: TemplateStringsArray): StatelessComponent<P>,
        blockquote<P>(values: TemplateStringsArray): StatelessComponent<P>,
        body<P>(values: TemplateStringsArray): StatelessComponent<P>,
        br<P>(values: TemplateStringsArray): StatelessComponent<P>,
        button<P>(values: TemplateStringsArray): StatelessComponent<P>,
        canvas<P>(values: TemplateStringsArray): StatelessComponent<P>,
        caption<P>(values: TemplateStringsArray): StatelessComponent<P>,
        cite<P>(values: TemplateStringsArray): StatelessComponent<P>,
        code<P>(values: TemplateStringsArray): StatelessComponent<P>,
        col<P>(values: TemplateStringsArray): StatelessComponent<P>,
        colgroup<P>(values: TemplateStringsArray): StatelessComponent<P>,
        data<P>(values: TemplateStringsArray): StatelessComponent<P>,
        datalist<P>(values: TemplateStringsArray): StatelessComponent<P>,
        dd<P>(values: TemplateStringsArray): StatelessComponent<P>,
        del<P>(values: TemplateStringsArray): StatelessComponent<P>,
        details<P>(values: TemplateStringsArray): StatelessComponent<P>,
        dfn<P>(values: TemplateStringsArray): StatelessComponent<P>,
        dialog<P>(values: TemplateStringsArray): StatelessComponent<P>,
        div<P>(values: TemplateStringsArray): StatelessComponent<P>,
        dl<P>(values: TemplateStringsArray): StatelessComponent<P>,
        dt<P>(values: TemplateStringsArray): StatelessComponent<P>,
        em<P>(values: TemplateStringsArray): StatelessComponent<P>,
        embed<P>(values: TemplateStringsArray): StatelessComponent<P>,
        fieldset<P>(values: TemplateStringsArray): StatelessComponent<P>,
        figcaption<P>(values: TemplateStringsArray): StatelessComponent<P>,
        figure<P>(values: TemplateStringsArray): StatelessComponent<P>,
        footer<P>(values: TemplateStringsArray): StatelessComponent<P>,
        form<P>(values: TemplateStringsArray): StatelessComponent<P>,
        h1<P>(values: TemplateStringsArray): StatelessComponent<P>,
        h2<P>(values: TemplateStringsArray): StatelessComponent<P>,
        h3<P>(values: TemplateStringsArray): StatelessComponent<P>,
        h4<P>(values: TemplateStringsArray): StatelessComponent<P>,
        h5<P>(values: TemplateStringsArray): StatelessComponent<P>,
        h6<P>(values: TemplateStringsArray): StatelessComponent<P>,
        head<P>(values: TemplateStringsArray): StatelessComponent<P>,
        header<P>(values: TemplateStringsArray): StatelessComponent<P>,
        hgroup<P>(values: TemplateStringsArray): StatelessComponent<P>,
        hr<P>(values: TemplateStringsArray): StatelessComponent<P>,
        html<P>(values: TemplateStringsArray): StatelessComponent<P>,
        i<P>(values: TemplateStringsArray): StatelessComponent<P>,
        iframe<P>(values: TemplateStringsArray): StatelessComponent<P>,
        img<P>(values: TemplateStringsArray): StatelessComponent<P>,
        input<P>(values: TemplateStringsArray): StatelessComponent<P>,
        ins<P>(values: TemplateStringsArray): StatelessComponent<P>,
        kbd<P>(values: TemplateStringsArray): StatelessComponent<P>,
        keygen<P>(values: TemplateStringsArray): StatelessComponent<P>,
        label<P>(values: TemplateStringsArray): StatelessComponent<P>,
        legend<P>(values: TemplateStringsArray): StatelessComponent<P>,
        li<P>(values: TemplateStringsArray): StatelessComponent<P>,
        link<P>(values: TemplateStringsArray): StatelessComponent<P>,
        main<P>(values: TemplateStringsArray): StatelessComponent<P>,
        map<P>(values: TemplateStringsArray): StatelessComponent<P>,
        mark<P>(values: TemplateStringsArray): StatelessComponent<P>,
        menu<P>(values: TemplateStringsArray): StatelessComponent<P>,
        menuitem<P>(values: TemplateStringsArray): StatelessComponent<P>,
        meta<P>(values: TemplateStringsArray): StatelessComponent<P>,
        meter<P>(values: TemplateStringsArray): StatelessComponent<P>,
        nav<P>(values: TemplateStringsArray): StatelessComponent<P>,
        noscript<P>(values: TemplateStringsArray): StatelessComponent<P>,
        object<P>(values: TemplateStringsArray): StatelessComponent<P>,
        ol<P>(values: TemplateStringsArray): StatelessComponent<P>,
        optgroup<P>(values: TemplateStringsArray): StatelessComponent<P>,
        option<P>(values: TemplateStringsArray): StatelessComponent<P>,
        output<P>(values: TemplateStringsArray): StatelessComponent<P>,
        p<P>(values: TemplateStringsArray): StatelessComponent<P>,
        param<P>(values: TemplateStringsArray): StatelessComponent<P>,
        picture<P>(values: TemplateStringsArray): StatelessComponent<P>,
        pre<P>(values: TemplateStringsArray): StatelessComponent<P>,
        progress<P>(values: TemplateStringsArray): StatelessComponent<P>,
        q<P>(values: TemplateStringsArray): StatelessComponent<P>,
        rp<P>(values: TemplateStringsArray): StatelessComponent<P>,
        rt<P>(values: TemplateStringsArray): StatelessComponent<P>,
        ruby<P>(values: TemplateStringsArray): StatelessComponent<P>,
        s<P>(values: TemplateStringsArray): StatelessComponent<P>,
        samp<P>(values: TemplateStringsArray): StatelessComponent<P>,
        script<P>(values: TemplateStringsArray): StatelessComponent<P>,
        section<P>(values: TemplateStringsArray): StatelessComponent<P>,
        select<P>(values: TemplateStringsArray): StatelessComponent<P>,
        small<P>(values: TemplateStringsArray): StatelessComponent<P>,
        source<P>(values: TemplateStringsArray): StatelessComponent<P>,
        span<P>(values: TemplateStringsArray): StatelessComponent<P>,
        strong<P>(values: TemplateStringsArray): StatelessComponent<P>,
        style<P>(values: TemplateStringsArray): StatelessComponent<P>,
        sub<P>(values: TemplateStringsArray): StatelessComponent<P>,
        summary<P>(values: TemplateStringsArray): StatelessComponent<P>,
        sup<P>(values: TemplateStringsArray): StatelessComponent<P>,
        table<P>(values: TemplateStringsArray): StatelessComponent<P>,
        tbody<P>(values: TemplateStringsArray): StatelessComponent<P>,
        td<P>(values: TemplateStringsArray): StatelessComponent<P>,
        textarea<P>(values: TemplateStringsArray): StatelessComponent<P>,
        tfoot<P>(values: TemplateStringsArray): StatelessComponent<P>,
        th<P>(values: TemplateStringsArray): StatelessComponent<P>,
        thead<P>(values: TemplateStringsArray): StatelessComponent<P>,
        time<P>(values: TemplateStringsArray): StatelessComponent<P>,
        title<P>(values: TemplateStringsArray): StatelessComponent<P>,
        tr<P>(values: TemplateStringsArray): StatelessComponent<P>,
        track<P>(values: TemplateStringsArray): StatelessComponent<P>,
        u<P>(values: TemplateStringsArray): StatelessComponent<P>,
        ul<P>(values: TemplateStringsArray): StatelessComponent<P>,
        // var<P>(values: TemplateStringsArray): StatelessComponent<P>,
        video<P>(values: TemplateStringsArray): StatelessComponent<P>,
        wbr<P>(values: TemplateStringsArray): StatelessComponent<P>,

        // SVG
        circle<P>(values: TemplateStringsArray): StatelessComponent<P>,
        clipPath<P>(values: TemplateStringsArray): StatelessComponent<P>,
        defs<P>(values: TemplateStringsArray): StatelessComponent<P>,
        ellipse<P>(values: TemplateStringsArray): StatelessComponent<P>,
        g<P>(values: TemplateStringsArray): StatelessComponent<P>,
        image<P>(values: TemplateStringsArray): StatelessComponent<P>,
        line<P>(values: TemplateStringsArray): StatelessComponent<P>,
        linearGradient<P>(values: TemplateStringsArray): StatelessComponent<P>,
        mask<P>(values: TemplateStringsArray): StatelessComponent<P>,
        path<P>(values: TemplateStringsArray): StatelessComponent<P>,
        pattern<P>(values: TemplateStringsArray): StatelessComponent<P>,
        polygon<P>(values: TemplateStringsArray): StatelessComponent<P>,
        polyline<P>(values: TemplateStringsArray): StatelessComponent<P>,
        radialGradient<P>(values: TemplateStringsArray): StatelessComponent<P>,
        rect<P>(values: TemplateStringsArray): StatelessComponent<P>,
        stop<P>(values: TemplateStringsArray): StatelessComponent<P>,
        svg<P>(values: TemplateStringsArray): StatelessComponent<P>,
        text<P>(values: TemplateStringsArray): StatelessComponent<P>,
        tspan<P>(values: TemplateStringsArray): StatelessComponent<P>,
    }

    var styled: StyledInterface;

    export default styled;
}