// <reference path="../react/react.d.ts" />

declare module 'styled-components' {
    import * as React from "react";
    import { StatelessComponent } from "react";


    interface StyledFunction<T> {
      (values: TemplateStringsArray): T,
      (...values: any[]): T,
    }

    interface StyledInterface {
        <T extends React.ReactType>(component: T): StyledFunction<T>,

        a: StyledFunction<React.ReactType>,
        abbr: StyledFunction<React.ReactType>,
        address: StyledFunction<React.ReactType>,
        area: StyledFunction<React.ReactType>,
        article: StyledFunction<React.ReactType>,
        aside: StyledFunction<React.ReactType>,
        audio: StyledFunction<React.ReactType>,
        b: StyledFunction<React.ReactType>,
        base: StyledFunction<React.ReactType>,
        bdi: StyledFunction<React.ReactType>,
        bdo: StyledFunction<React.ReactType>,
        big: StyledFunction<React.ReactType>,
        blockquote: StyledFunction<React.ReactType>,
        body: StyledFunction<React.ReactType>,
        br: StyledFunction<React.ReactType>,
        button: StyledFunction<React.ReactType>,
        canvas: StyledFunction<React.ReactType>,
        caption: StyledFunction<React.ReactType>,
        cite: StyledFunction<React.ReactType>,
        code: StyledFunction<React.ReactType>,
        col: StyledFunction<React.ReactType>,
        colgroup: StyledFunction<React.ReactType>,
        data: StyledFunction<React.ReactType>,
        datalist: StyledFunction<React.ReactType>,
        dd: StyledFunction<React.ReactType>,
        del: StyledFunction<React.ReactType>,
        details: StyledFunction<React.ReactType>,
        dfn: StyledFunction<React.ReactType>,
        dialog: StyledFunction<React.ReactType>,
        div: StyledFunction<React.ReactType>,
        dl: StyledFunction<React.ReactType>,
        dt: StyledFunction<React.ReactType>,
        em: StyledFunction<React.ReactType>,
        embed: StyledFunction<React.ReactType>,
        fieldset: StyledFunction<React.ReactType>,
        figcaption: StyledFunction<React.ReactType>,
        figure: StyledFunction<React.ReactType>,
        footer: StyledFunction<React.ReactType>,
        form: StyledFunction<React.ReactType>,
        h1: StyledFunction<React.ReactType>,
        h2: StyledFunction<React.ReactType>,
        h3: StyledFunction<React.ReactType>,
        h4: StyledFunction<React.ReactType>,
        h5: StyledFunction<React.ReactType>,
        h6: StyledFunction<React.ReactType>,
        head: StyledFunction<React.ReactType>,
        header: StyledFunction<React.ReactType>,
        hgroup: StyledFunction<React.ReactType>,
        hr: StyledFunction<React.ReactType>,
        html: StyledFunction<React.ReactType>,
        i: StyledFunction<React.ReactType>,
        iframe: StyledFunction<React.ReactType>,
        img: StyledFunction<React.ReactType>,
        input: StyledFunction<React.ReactType>,
        ins: StyledFunction<React.ReactType>,
        kbd: StyledFunction<React.ReactType>,
        keygen: StyledFunction<React.ReactType>,
        label: StyledFunction<React.ReactType>,
        legend: StyledFunction<React.ReactType>,
        li: StyledFunction<React.ReactType>,
        link: StyledFunction<React.ReactType>,
        main: StyledFunction<React.ReactType>,
        map: StyledFunction<React.ReactType>,
        mark: StyledFunction<React.ReactType>,
        menu: StyledFunction<React.ReactType>,
        menuitem: StyledFunction<React.ReactType>,
        meta: StyledFunction<React.ReactType>,
        meter: StyledFunction<React.ReactType>,
        nav: StyledFunction<React.ReactType>,
        noscript: StyledFunction<React.ReactType>,
        object: StyledFunction<React.ReactType>,
        ol: StyledFunction<React.ReactType>,
        optgroup: StyledFunction<React.ReactType>,
        option: StyledFunction<React.ReactType>,
        output: StyledFunction<React.ReactType>,
        p: StyledFunction<React.ReactType>,
        param: StyledFunction<React.ReactType>,
        picture: StyledFunction<React.ReactType>,
        pre: StyledFunction<React.ReactType>,
        progress: StyledFunction<React.ReactType>,
        q: StyledFunction<React.ReactType>,
        rp: StyledFunction<React.ReactType>,
        rt: StyledFunction<React.ReactType>,
        ruby: StyledFunction<React.ReactType>,
        s: StyledFunction<React.ReactType>,
        samp: StyledFunction<React.ReactType>,
        script: StyledFunction<React.ReactType>,
        section: StyledFunction<React.ReactType>,
        select: StyledFunction<React.ReactType>,
        small: StyledFunction<React.ReactType>,
        source: StyledFunction<React.ReactType>,
        span: StyledFunction<React.ReactType>,
        strong: StyledFunction<React.ReactType>,
        style: StyledFunction<React.ReactType>,
        sub: StyledFunction<React.ReactType>,
        summary: StyledFunction<React.ReactType>,
        sup: StyledFunction<React.ReactType>,
        table: StyledFunction<React.ReactType>,
        tbody: StyledFunction<React.ReactType>,
        td: StyledFunction<React.ReactType>,
        textarea: StyledFunction<React.ReactType>,
        tfoot: StyledFunction<React.ReactType>,
        th: StyledFunction<React.ReactType>,
        thead: StyledFunction<React.ReactType>,
        time: StyledFunction<React.ReactType>,
        title: StyledFunction<React.ReactType>,
        tr: StyledFunction<React.ReactType>,
        track: StyledFunction<React.ReactType>,
        u: StyledFunction<React.ReactType>,
        ul: StyledFunction<React.ReactType>,
        var: StyledFunction<React.ReactType>,
        video: StyledFunction<React.ReactType>,
        wbr: StyledFunction<React.ReactType>,

        // SVG
        circle: StyledFunction<React.ReactType>,
        clipPath: StyledFunction<React.ReactType>,
        defs: StyledFunction<React.ReactType>,
        ellipse: StyledFunction<React.ReactType>,
        g: StyledFunction<React.ReactType>,
        image: StyledFunction<React.ReactType>,
        line: StyledFunction<React.ReactType>,
        linearGradient: StyledFunction<React.ReactType>,
        mask: StyledFunction<React.ReactType>,
        path: StyledFunction<React.ReactType>,
        pattern: StyledFunction<React.ReactType>,
        polygon: StyledFunction<React.ReactType>,
        polyline: StyledFunction<React.ReactType>,
        radialGradient: StyledFunction<React.ReactType>,
        rect: StyledFunction<React.ReactType>,
        stop: StyledFunction<React.ReactType>,
        svg: StyledFunction<React.ReactType>,
        text: StyledFunction<React.ReactType>,
        tspan: StyledFunction<React.ReactType>,
    }

    var styled: StyledInterface;

    export default styled;
}
