// @flow

/* eslint-disable import/no-unresolved */
import {
  AccessibilityInfo,
  ActivityIndicator,
  ReactNativeART,
  Button,
  CheckBox,
  DatePickerIOS,
  DrawerLayoutAndroid,
  FlatList,
  Image,
  ImageBackground,
  ImageEditor,
  ImageStore,
  InputAccessoryView,
  KeyboardAvoidingView,
  ListView,
  MaskedViewIOS,
  Modal,
  NavigatorIOS,
  Picker,
  PickerIOS,
  ProgressBarAndroid,
  ProgressViewIOS,
  SafeAreaView,
  ScrollView,
  SectionList,
  SegmentedControlIOS,
  Slider,
  SnapshotViewIOS,
  Switch,
  RefreshControl,
  StatusBar,
  SwipeableFlatList,
  SwipeableListView,
  TabBarIOS,
  Text,
  TextInput,
  ToastAndroid,
  ToolbarAndroid,
  Touchable,
  TouchableHighlight,
  TouchableNativeFeedback,
  TouchableOpacity,
  TouchableWithoutFeedback,
  View,
  ViewPagerAndroid,
  VirtualizedList,
  WebView,
  ActionSheetIOS,
  Alert,
  AlertIOS,
  Animated,
  AppRegistry,
  AppState,
  AsyncStorage,
  BackAndroid,
  BackHandler,
  CameraRoll,
  Clipboard,
  DatePickerAndroid,
  DeviceInfo,
  Dimensions,
  Easing,
  findNodeHandle,
  I18nManager,
  ImagePickerIOS,
  InteractionManager,
  Keyboard,
  LayoutAnimation,
  Linking,
  NativeEventEmitter,
  NetInfo,
  PanResponder,
  PermissionsAndroid,
  PixelRatio,
  PushNotificationIOS,
  Settings,
  Share,
  StatusBarIOS,
  StyleSheet,
  Systrace,
  TimePickerAndroid,
  TVEventHandler,
  UIManager,
  unstable_batchedUpdates,
  Vibration,
  VibrationIOS,
  YellowBox,
  DeviceEventEmitter,
  NativeAppEventEmitter,
  NativeModules,
  Platform,
  processColor,
  requireNativeComponent,
  takeSnapshot,
  ColorPropType,
  EdgeInsetsPropType,
  PointPropType,
  ViewPropTypes,
} from 'react-native';

const reactNative = {
  AccessibilityInfo,
  ActivityIndicator,
  ReactNativeART,
  Button,
  CheckBox,
  DatePickerIOS,
  DrawerLayoutAndroid,
  FlatList,
  Image,
  ImageBackground,
  ImageEditor,
  ImageStore,
  InputAccessoryView,
  KeyboardAvoidingView,
  ListView,
  MaskedViewIOS,
  Modal,
  NavigatorIOS,
  Picker,
  PickerIOS,
  ProgressBarAndroid,
  ProgressViewIOS,
  SafeAreaView,
  ScrollView,
  SectionList,
  SegmentedControlIOS,
  Slider,
  SnapshotViewIOS,
  Switch,
  RefreshControl,
  StatusBar,
  SwipeableFlatList,
  SwipeableListView,
  TabBarIOS,
  Text,
  TextInput,
  ToastAndroid,
  ToolbarAndroid,
  Touchable,
  TouchableHighlight,
  TouchableNativeFeedback,
  TouchableOpacity,
  TouchableWithoutFeedback,
  View,
  ViewPagerAndroid,
  VirtualizedList,
  WebView,
  ActionSheetIOS,
  Alert,
  AlertIOS,
  Animated,
  AppRegistry,
  AppState,
  AsyncStorage,
  BackAndroid,
  BackHandler,
  CameraRoll,
  Clipboard,
  DatePickerAndroid,
  DeviceInfo,
  Dimensions,
  Easing,
  findNodeHandle,
  I18nManager,
  ImagePickerIOS,
  InteractionManager,
  Keyboard,
  LayoutAnimation,
  Linking,
  NativeEventEmitter,
  NetInfo,
  PanResponder,
  PermissionsAndroid,
  PixelRatio,
  PushNotificationIOS,
  Settings,
  Share,
  StatusBarIOS,
  StyleSheet,
  Systrace,
  TimePickerAndroid,
  TVEventHandler,
  UIManager,
  unstable_batchedUpdates,
  Vibration,
  VibrationIOS,
  YellowBox,
  DeviceEventEmitter,
  NativeAppEventEmitter,
  NativeModules,
  Platform,
  processColor,
  requireNativeComponent,
  takeSnapshot,
  ColorPropType,
  EdgeInsetsPropType,
  PointPropType,
  ViewPropTypes
};

import _InlineStyle from '../models/InlineStyle';
import _StyledNativeComponent from '../models/StyledNativeComponent';

import css from '../constructors/css';
import constructWithOptions from '../constructors/constructWithOptions';
import ThemeProvider, { ThemeConsumer, ThemeContext } from '../models/ThemeProvider';
import withTheme from '../hoc/withTheme';
import isStyledComponent from '../utils/isStyledComponent';

import type { Target } from '../types';

const InlineStyle = _InlineStyle(reactNative.StyleSheet);
const StyledNativeComponent = _StyledNativeComponent(InlineStyle);
const styled = (tag: Target) => constructWithOptions(StyledNativeComponent, tag);

/* React native lazy-requires each of these modules for some reason, so let's
 *  assume it's for a good reason and not eagerly load them all */
const aliases = `ActivityIndicator ActivityIndicatorIOS ART Button DatePickerIOS DrawerLayoutAndroid
 Image ImageBackground ImageEditor ImageStore KeyboardAvoidingView ListView MapView Modal NavigatorIOS
 Picker PickerIOS ProgressBarAndroid ProgressViewIOS ScrollView SegmentedControlIOS Slider
 SliderIOS SnapshotViewIOS Switch RecyclerViewBackedScrollView RefreshControl SafeAreaView StatusBar
 SwipeableListView SwitchAndroid SwitchIOS TabBarIOS Text TextInput ToastAndroid ToolbarAndroid
 Touchable TouchableHighlight TouchableNativeFeedback TouchableOpacity TouchableWithoutFeedback
 View ViewPagerAndroid WebView FlatList SectionList VirtualizedList`;

/* Define a getter for each alias which simply gets the reactNative component
 * and passes it to styled */
aliases.split(/\s+/m).forEach(alias =>
  Object.defineProperty(styled, alias, {
    enumerable: true,
    configurable: false,
    get() {
      return styled(reactNative[alias]);
    },
  })
);

export { css, isStyledComponent, ThemeProvider, ThemeConsumer, ThemeContext, withTheme };
export default styled;
