// flow-typed signature: b1b8313491cb94525eb1bdafc557289e
// flow-typed version: <<STUB>>/acorn_v6.1.1/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'acorn'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'acorn' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'acorn/dist/acorn' {
  declare module.exports: any;
}

declare module 'acorn/dist/bin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'acorn/dist/acorn.js' {
  declare module.exports: $Exports<'acorn/dist/acorn'>;
}
declare module 'acorn/dist/bin.js' {
  declare module.exports: $Exports<'acorn/dist/bin'>;
}
