// flow-typed signature: e2ffbde0ceca6a67a65e3e5fc3a808cb
// flow-typed version: <<STUB>>/babel-plugin-styled-components_vvx.x.x.js/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-styled-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-styled-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-styled-components/lib/css/placeholderUtils' {
  declare module.exports: any;
}

declare module 'babel-plugin-styled-components/lib/css/preprocess' {
  declare module.exports: any;
}

declare module 'babel-plugin-styled-components/lib/css/preprocessInjectGlobal' {
  declare module.exports: any;
}

declare module 'babel-plugin-styled-components/lib/css/preprocessKeyframes' {
  declare module.exports: any;
}

declare module 'babel-plugin-styled-components/lib/css/preprocessUtils' {
  declare module.exports: any;
}

declare module 'babel-plugin-styled-components/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-styled-components/lib/minify/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-styled-components/lib/utils/detectors' {
  declare module.exports: any;
}

declare module 'babel-plugin-styled-components/lib/utils/getName' {
  declare module.exports: any;
}

declare module 'babel-plugin-styled-components/lib/utils/hash' {
  declare module.exports: any;
}

declare module 'babel-plugin-styled-components/lib/utils/options' {
  declare module.exports: any;
}

declare module 'babel-plugin-styled-components/lib/visitors/displayNameAndId' {
  declare module.exports: any;
}

declare module 'babel-plugin-styled-components/lib/visitors/minify' {
  declare module.exports: any;
}

declare module 'babel-plugin-styled-components/lib/visitors/noParserImport' {
  declare module.exports: any;
}

declare module 'babel-plugin-styled-components/lib/visitors/templateLiterals' {
  declare module.exports: any;
}

declare module 'babel-plugin-styled-components/lib/visitors/templateLiterals/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-styled-components/lib/visitors/templateLiterals/preprocess' {
  declare module.exports: any;
}

declare module 'babel-plugin-styled-components/lib/visitors/templateLiterals/transpile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-styled-components/lib/css/placeholderUtils.js' {
  declare module.exports: $Exports<'babel-plugin-styled-components/lib/css/placeholderUtils'>;
}
declare module 'babel-plugin-styled-components/lib/css/preprocess.js' {
  declare module.exports: $Exports<'babel-plugin-styled-components/lib/css/preprocess'>;
}
declare module 'babel-plugin-styled-components/lib/css/preprocessInjectGlobal.js' {
  declare module.exports: $Exports<'babel-plugin-styled-components/lib/css/preprocessInjectGlobal'>;
}
declare module 'babel-plugin-styled-components/lib/css/preprocessKeyframes.js' {
  declare module.exports: $Exports<'babel-plugin-styled-components/lib/css/preprocessKeyframes'>;
}
declare module 'babel-plugin-styled-components/lib/css/preprocessUtils.js' {
  declare module.exports: $Exports<'babel-plugin-styled-components/lib/css/preprocessUtils'>;
}
declare module 'babel-plugin-styled-components/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-styled-components/lib/index'>;
}
declare module 'babel-plugin-styled-components/lib/minify/index.js' {
  declare module.exports: $Exports<'babel-plugin-styled-components/lib/minify/index'>;
}
declare module 'babel-plugin-styled-components/lib/utils/detectors.js' {
  declare module.exports: $Exports<'babel-plugin-styled-components/lib/utils/detectors'>;
}
declare module 'babel-plugin-styled-components/lib/utils/getName.js' {
  declare module.exports: $Exports<'babel-plugin-styled-components/lib/utils/getName'>;
}
declare module 'babel-plugin-styled-components/lib/utils/hash.js' {
  declare module.exports: $Exports<'babel-plugin-styled-components/lib/utils/hash'>;
}
declare module 'babel-plugin-styled-components/lib/utils/options.js' {
  declare module.exports: $Exports<'babel-plugin-styled-components/lib/utils/options'>;
}
declare module 'babel-plugin-styled-components/lib/visitors/displayNameAndId.js' {
  declare module.exports: $Exports<'babel-plugin-styled-components/lib/visitors/displayNameAndId'>;
}
declare module 'babel-plugin-styled-components/lib/visitors/minify.js' {
  declare module.exports: $Exports<'babel-plugin-styled-components/lib/visitors/minify'>;
}
declare module 'babel-plugin-styled-components/lib/visitors/noParserImport.js' {
  declare module.exports: $Exports<'babel-plugin-styled-components/lib/visitors/noParserImport'>;
}
declare module 'babel-plugin-styled-components/lib/visitors/templateLiterals/index.js' {
  declare module.exports: $Exports<'babel-plugin-styled-components/lib/visitors/templateLiterals/index'>;
}
declare module 'babel-plugin-styled-components/lib/visitors/templateLiterals/preprocess.js' {
  declare module.exports: $Exports<'babel-plugin-styled-components/lib/visitors/templateLiterals/preprocess'>;
}
declare module 'babel-plugin-styled-components/lib/visitors/templateLiterals/transpile.js' {
  declare module.exports: $Exports<'babel-plugin-styled-components/lib/visitors/templateLiterals/transpile'>;
}
