// flow-typed signature: d5a34316b236f0be91f5fe8903b9613b
// flow-typed version: <<STUB>>/babel-macros_vvx.x.x.js/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-macros'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-macros' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-macros/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-macros/dist/index.js' {
  declare module.exports: $Exports<'babel-macros/dist/index'>;
}
