// flow-typed signature: 24c3ba141e10789cfb8fcea09e15919e
// flow-typed version: <<STUB>>/babel-core_v^7.0.0-bridge.0/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-core/index' {
  declare module.exports: $Exports<'babel-core'>;
}
declare module 'babel-core/index.js' {
  declare module.exports: $Exports<'babel-core'>;
}
