// flow-typed signature: 161dc0f5d83c32fe4b26ed89278069ea
// flow-typed version: <<STUB>>/babel-preset-latest_v^6.14.0/flow_v0.32.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-latest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-latest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-latest/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-latest/lib/index.js' {
  declare module.exports: $Exports<'babel-preset-latest/lib/index'>;
}
