// flow-typed signature: b98d2b4e31607810c9803acbffcc8428
// flow-typed version: <<STUB>>/babel-plugin-macros_v^2.5.1/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-macros'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-macros' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-macros/dist/__tests__/create-macros' {
  declare module.exports: any;
}

declare module 'babel-plugin-macros/dist/__tests__/fixtures/config/babel-plugin-macros.config' {
  declare module.exports: any;
}

declare module 'babel-plugin-macros/dist/__tests__/fixtures/config/code' {
  declare module.exports: any;
}

declare module 'babel-plugin-macros/dist/__tests__/fixtures/config/configurable.macro' {
  declare module.exports: any;
}

declare module 'babel-plugin-macros/dist/__tests__/fixtures/emotion-esm.macro' {
  declare module.exports: any;
}

declare module 'babel-plugin-macros/dist/__tests__/fixtures/emotion.macro' {
  declare module.exports: any;
}

declare module 'babel-plugin-macros/dist/__tests__/fixtures/error-thrower.macro' {
  declare module.exports: any;
}

declare module 'babel-plugin-macros/dist/__tests__/fixtures/eval.macro' {
  declare module.exports: any;
}

declare module 'babel-plugin-macros/dist/__tests__/fixtures/jsx-id-prefix.macro' {
  declare module.exports: any;
}

declare module 'babel-plugin-macros/dist/__tests__/fixtures/jsx-id-prefix.plugin' {
  declare module.exports: any;
}

declare module 'babel-plugin-macros/dist/__tests__/fixtures/keep-imports.macro' {
  declare module.exports: any;
}

declare module 'babel-plugin-macros/dist/__tests__/fixtures/macro-error-thrower.macro' {
  declare module.exports: any;
}

declare module 'babel-plugin-macros/dist/__tests__/fixtures/non-wrapped.macro' {
  declare module.exports: any;
}

declare module 'babel-plugin-macros/dist/__tests__/fixtures/path-replace-issue/variable-assignment' {
  declare module.exports: any;
}

declare module 'babel-plugin-macros/dist/__tests__/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-macros/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-macros/dist/__tests__/create-macros.js' {
  declare module.exports: $Exports<'babel-plugin-macros/dist/__tests__/create-macros'>;
}
declare module 'babel-plugin-macros/dist/__tests__/fixtures/config/babel-plugin-macros.config.js' {
  declare module.exports: $Exports<'babel-plugin-macros/dist/__tests__/fixtures/config/babel-plugin-macros.config'>;
}
declare module 'babel-plugin-macros/dist/__tests__/fixtures/config/code.js' {
  declare module.exports: $Exports<'babel-plugin-macros/dist/__tests__/fixtures/config/code'>;
}
declare module 'babel-plugin-macros/dist/__tests__/fixtures/config/configurable.macro.js' {
  declare module.exports: $Exports<'babel-plugin-macros/dist/__tests__/fixtures/config/configurable.macro'>;
}
declare module 'babel-plugin-macros/dist/__tests__/fixtures/emotion-esm.macro.js' {
  declare module.exports: $Exports<'babel-plugin-macros/dist/__tests__/fixtures/emotion-esm.macro'>;
}
declare module 'babel-plugin-macros/dist/__tests__/fixtures/emotion.macro.js' {
  declare module.exports: $Exports<'babel-plugin-macros/dist/__tests__/fixtures/emotion.macro'>;
}
declare module 'babel-plugin-macros/dist/__tests__/fixtures/error-thrower.macro.js' {
  declare module.exports: $Exports<'babel-plugin-macros/dist/__tests__/fixtures/error-thrower.macro'>;
}
declare module 'babel-plugin-macros/dist/__tests__/fixtures/eval.macro.js' {
  declare module.exports: $Exports<'babel-plugin-macros/dist/__tests__/fixtures/eval.macro'>;
}
declare module 'babel-plugin-macros/dist/__tests__/fixtures/jsx-id-prefix.macro.js' {
  declare module.exports: $Exports<'babel-plugin-macros/dist/__tests__/fixtures/jsx-id-prefix.macro'>;
}
declare module 'babel-plugin-macros/dist/__tests__/fixtures/jsx-id-prefix.plugin.js' {
  declare module.exports: $Exports<'babel-plugin-macros/dist/__tests__/fixtures/jsx-id-prefix.plugin'>;
}
declare module 'babel-plugin-macros/dist/__tests__/fixtures/keep-imports.macro.js' {
  declare module.exports: $Exports<'babel-plugin-macros/dist/__tests__/fixtures/keep-imports.macro'>;
}
declare module 'babel-plugin-macros/dist/__tests__/fixtures/macro-error-thrower.macro.js' {
  declare module.exports: $Exports<'babel-plugin-macros/dist/__tests__/fixtures/macro-error-thrower.macro'>;
}
declare module 'babel-plugin-macros/dist/__tests__/fixtures/non-wrapped.macro.js' {
  declare module.exports: $Exports<'babel-plugin-macros/dist/__tests__/fixtures/non-wrapped.macro'>;
}
declare module 'babel-plugin-macros/dist/__tests__/fixtures/path-replace-issue/variable-assignment.js' {
  declare module.exports: $Exports<'babel-plugin-macros/dist/__tests__/fixtures/path-replace-issue/variable-assignment'>;
}
declare module 'babel-plugin-macros/dist/__tests__/index.js' {
  declare module.exports: $Exports<'babel-plugin-macros/dist/__tests__/index'>;
}
declare module 'babel-plugin-macros/dist/index.js' {
  declare module.exports: $Exports<'babel-plugin-macros/dist/index'>;
}
