// flow-typed signature: 1b3c06f2d20b0b0dba21d781882e8561
// flow-typed version: <<STUB>>/babel-eslint_v^10.0.1/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-eslint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-eslint/lib/analyze-scope' {
  declare module.exports: any;
}

declare module 'babel-eslint/lib/babylon-to-espree/attachComments' {
  declare module.exports: any;
}

declare module 'babel-eslint/lib/babylon-to-espree/convertComments' {
  declare module.exports: any;
}

declare module 'babel-eslint/lib/babylon-to-espree/convertTemplateType' {
  declare module.exports: any;
}

declare module 'babel-eslint/lib/babylon-to-espree/index' {
  declare module.exports: any;
}

declare module 'babel-eslint/lib/babylon-to-espree/toAST' {
  declare module.exports: any;
}

declare module 'babel-eslint/lib/babylon-to-espree/toToken' {
  declare module.exports: any;
}

declare module 'babel-eslint/lib/babylon-to-espree/toTokens' {
  declare module.exports: any;
}

declare module 'babel-eslint/lib/index' {
  declare module.exports: any;
}

declare module 'babel-eslint/lib/parse-with-scope' {
  declare module.exports: any;
}

declare module 'babel-eslint/lib/parse' {
  declare module.exports: any;
}

declare module 'babel-eslint/lib/visitor-keys' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-eslint/lib/analyze-scope.js' {
  declare module.exports: $Exports<'babel-eslint/lib/analyze-scope'>;
}
declare module 'babel-eslint/lib/babylon-to-espree/attachComments.js' {
  declare module.exports: $Exports<'babel-eslint/lib/babylon-to-espree/attachComments'>;
}
declare module 'babel-eslint/lib/babylon-to-espree/convertComments.js' {
  declare module.exports: $Exports<'babel-eslint/lib/babylon-to-espree/convertComments'>;
}
declare module 'babel-eslint/lib/babylon-to-espree/convertTemplateType.js' {
  declare module.exports: $Exports<'babel-eslint/lib/babylon-to-espree/convertTemplateType'>;
}
declare module 'babel-eslint/lib/babylon-to-espree/index.js' {
  declare module.exports: $Exports<'babel-eslint/lib/babylon-to-espree/index'>;
}
declare module 'babel-eslint/lib/babylon-to-espree/toAST.js' {
  declare module.exports: $Exports<'babel-eslint/lib/babylon-to-espree/toAST'>;
}
declare module 'babel-eslint/lib/babylon-to-espree/toToken.js' {
  declare module.exports: $Exports<'babel-eslint/lib/babylon-to-espree/toToken'>;
}
declare module 'babel-eslint/lib/babylon-to-espree/toTokens.js' {
  declare module.exports: $Exports<'babel-eslint/lib/babylon-to-espree/toTokens'>;
}
declare module 'babel-eslint/lib/index.js' {
  declare module.exports: $Exports<'babel-eslint/lib/index'>;
}
declare module 'babel-eslint/lib/parse-with-scope.js' {
  declare module.exports: $Exports<'babel-eslint/lib/parse-with-scope'>;
}
declare module 'babel-eslint/lib/parse.js' {
  declare module.exports: $Exports<'babel-eslint/lib/parse'>;
}
declare module 'babel-eslint/lib/visitor-keys.js' {
  declare module.exports: $Exports<'babel-eslint/lib/visitor-keys'>;
}
