// flow-typed signature: eed5600049365a92858c0b11e6fb667e
// flow-typed version: <<STUB>>/babel-plugin-tester_v^6.0.1/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-tester'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-tester' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-tester/dist/__mocks__/@babel/core' {
  declare module.exports: any;
}

declare module 'babel-plugin-tester/dist/__tests__/fixtures/failing-fixtures/failure/code' {
  declare module.exports: any;
}

declare module 'babel-plugin-tester/dist/__tests__/fixtures/failing-fixtures/failure/output' {
  declare module.exports: any;
}

declare module 'babel-plugin-tester/dist/__tests__/fixtures/fixture1' {
  declare module.exports: any;
}

declare module 'babel-plugin-tester/dist/__tests__/fixtures/fixtures/changed/code' {
  declare module.exports: any;
}

declare module 'babel-plugin-tester/dist/__tests__/fixtures/fixtures/changed/output' {
  declare module.exports: any;
}

declare module 'babel-plugin-tester/dist/__tests__/fixtures/fixtures/nested/nested-a/code' {
  declare module.exports: any;
}

declare module 'babel-plugin-tester/dist/__tests__/fixtures/fixtures/nested/nested-a/output' {
  declare module.exports: any;
}

declare module 'babel-plugin-tester/dist/__tests__/fixtures/fixtures/nested/nested-b/code' {
  declare module.exports: any;
}

declare module 'babel-plugin-tester/dist/__tests__/fixtures/fixtures/nested/nested-b/output' {
  declare module.exports: any;
}

declare module 'babel-plugin-tester/dist/__tests__/fixtures/fixtures/unchanged/code' {
  declare module.exports: any;
}

declare module 'babel-plugin-tester/dist/__tests__/fixtures/fixtures/unchanged/output' {
  declare module.exports: any;
}

declare module 'babel-plugin-tester/dist/__tests__/fixtures/fixtures/without-output-file/code' {
  declare module.exports: any;
}

declare module 'babel-plugin-tester/dist/__tests__/fixtures/outure1' {
  declare module.exports: any;
}

declare module 'babel-plugin-tester/dist/__tests__/helpers/identifier-reverse-plugin' {
  declare module.exports: any;
}

declare module 'babel-plugin-tester/dist/__tests__/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-tester/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-tester/dist/__mocks__/@babel/core.js' {
  declare module.exports: $Exports<'babel-plugin-tester/dist/__mocks__/@babel/core'>;
}
declare module 'babel-plugin-tester/dist/__tests__/fixtures/failing-fixtures/failure/code.js' {
  declare module.exports: $Exports<'babel-plugin-tester/dist/__tests__/fixtures/failing-fixtures/failure/code'>;
}
declare module 'babel-plugin-tester/dist/__tests__/fixtures/failing-fixtures/failure/output.js' {
  declare module.exports: $Exports<'babel-plugin-tester/dist/__tests__/fixtures/failing-fixtures/failure/output'>;
}
declare module 'babel-plugin-tester/dist/__tests__/fixtures/fixture1.js' {
  declare module.exports: $Exports<'babel-plugin-tester/dist/__tests__/fixtures/fixture1'>;
}
declare module 'babel-plugin-tester/dist/__tests__/fixtures/fixtures/changed/code.js' {
  declare module.exports: $Exports<'babel-plugin-tester/dist/__tests__/fixtures/fixtures/changed/code'>;
}
declare module 'babel-plugin-tester/dist/__tests__/fixtures/fixtures/changed/output.js' {
  declare module.exports: $Exports<'babel-plugin-tester/dist/__tests__/fixtures/fixtures/changed/output'>;
}
declare module 'babel-plugin-tester/dist/__tests__/fixtures/fixtures/nested/nested-a/code.js' {
  declare module.exports: $Exports<'babel-plugin-tester/dist/__tests__/fixtures/fixtures/nested/nested-a/code'>;
}
declare module 'babel-plugin-tester/dist/__tests__/fixtures/fixtures/nested/nested-a/output.js' {
  declare module.exports: $Exports<'babel-plugin-tester/dist/__tests__/fixtures/fixtures/nested/nested-a/output'>;
}
declare module 'babel-plugin-tester/dist/__tests__/fixtures/fixtures/nested/nested-b/code.js' {
  declare module.exports: $Exports<'babel-plugin-tester/dist/__tests__/fixtures/fixtures/nested/nested-b/code'>;
}
declare module 'babel-plugin-tester/dist/__tests__/fixtures/fixtures/nested/nested-b/output.js' {
  declare module.exports: $Exports<'babel-plugin-tester/dist/__tests__/fixtures/fixtures/nested/nested-b/output'>;
}
declare module 'babel-plugin-tester/dist/__tests__/fixtures/fixtures/unchanged/code.js' {
  declare module.exports: $Exports<'babel-plugin-tester/dist/__tests__/fixtures/fixtures/unchanged/code'>;
}
declare module 'babel-plugin-tester/dist/__tests__/fixtures/fixtures/unchanged/output.js' {
  declare module.exports: $Exports<'babel-plugin-tester/dist/__tests__/fixtures/fixtures/unchanged/output'>;
}
declare module 'babel-plugin-tester/dist/__tests__/fixtures/fixtures/without-output-file/code.js' {
  declare module.exports: $Exports<'babel-plugin-tester/dist/__tests__/fixtures/fixtures/without-output-file/code'>;
}
declare module 'babel-plugin-tester/dist/__tests__/fixtures/outure1.js' {
  declare module.exports: $Exports<'babel-plugin-tester/dist/__tests__/fixtures/outure1'>;
}
declare module 'babel-plugin-tester/dist/__tests__/helpers/identifier-reverse-plugin.js' {
  declare module.exports: $Exports<'babel-plugin-tester/dist/__tests__/helpers/identifier-reverse-plugin'>;
}
declare module 'babel-plugin-tester/dist/__tests__/index.js' {
  declare module.exports: $Exports<'babel-plugin-tester/dist/__tests__/index'>;
}
declare module 'babel-plugin-tester/dist/index.js' {
  declare module.exports: $Exports<'babel-plugin-tester/dist/index'>;
}
