// flow-typed signature: eee04c0c136a7d1c85ecf45e4ca307e5
// flow-typed version: <<STUB>>/babel-plugin-add-module-exports_v^1.0.2/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-add-module-exports'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-add-module-exports' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-add-module-exports/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-add-module-exports/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-add-module-exports/lib/index'>;
}
