// flow-typed signature: 3631573e8a31615f5c06edf208a5d931
// flow-typed version: <<STUB>>/babel-plugin-styled-components_v>= 1/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-styled-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-styled-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-styled-components/lib/css/placeholderUtils' {
  declare module.exports: any;
}

declare module 'babel-plugin-styled-components/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-styled-components/lib/minify/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-styled-components/lib/utils/detectors' {
  declare module.exports: any;
}

declare module 'babel-plugin-styled-components/lib/utils/getName' {
  declare module.exports: any;
}

declare module 'babel-plugin-styled-components/lib/utils/hash' {
  declare module.exports: any;
}

declare module 'babel-plugin-styled-components/lib/utils/options' {
  declare module.exports: any;
}

declare module 'babel-plugin-styled-components/lib/utils/prefixDigit' {
  declare module.exports: any;
}

declare module 'babel-plugin-styled-components/lib/visitors/assignStyledRequired' {
  declare module.exports: any;
}

declare module 'babel-plugin-styled-components/lib/visitors/displayNameAndId' {
  declare module.exports: any;
}

declare module 'babel-plugin-styled-components/lib/visitors/minify' {
  declare module.exports: any;
}

declare module 'babel-plugin-styled-components/lib/visitors/pure' {
  declare module.exports: any;
}

declare module 'babel-plugin-styled-components/lib/visitors/templateLiterals/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-styled-components/lib/visitors/templateLiterals/transpile' {
  declare module.exports: any;
}

declare module 'babel-plugin-styled-components/lib/visitors/transpileCssProp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-styled-components/lib/css/placeholderUtils.js' {
  declare module.exports: $Exports<'babel-plugin-styled-components/lib/css/placeholderUtils'>;
}
declare module 'babel-plugin-styled-components/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-styled-components/lib/index'>;
}
declare module 'babel-plugin-styled-components/lib/minify/index.js' {
  declare module.exports: $Exports<'babel-plugin-styled-components/lib/minify/index'>;
}
declare module 'babel-plugin-styled-components/lib/utils/detectors.js' {
  declare module.exports: $Exports<'babel-plugin-styled-components/lib/utils/detectors'>;
}
declare module 'babel-plugin-styled-components/lib/utils/getName.js' {
  declare module.exports: $Exports<'babel-plugin-styled-components/lib/utils/getName'>;
}
declare module 'babel-plugin-styled-components/lib/utils/hash.js' {
  declare module.exports: $Exports<'babel-plugin-styled-components/lib/utils/hash'>;
}
declare module 'babel-plugin-styled-components/lib/utils/options.js' {
  declare module.exports: $Exports<'babel-plugin-styled-components/lib/utils/options'>;
}
declare module 'babel-plugin-styled-components/lib/utils/prefixDigit.js' {
  declare module.exports: $Exports<'babel-plugin-styled-components/lib/utils/prefixDigit'>;
}
declare module 'babel-plugin-styled-components/lib/visitors/assignStyledRequired.js' {
  declare module.exports: $Exports<'babel-plugin-styled-components/lib/visitors/assignStyledRequired'>;
}
declare module 'babel-plugin-styled-components/lib/visitors/displayNameAndId.js' {
  declare module.exports: $Exports<'babel-plugin-styled-components/lib/visitors/displayNameAndId'>;
}
declare module 'babel-plugin-styled-components/lib/visitors/minify.js' {
  declare module.exports: $Exports<'babel-plugin-styled-components/lib/visitors/minify'>;
}
declare module 'babel-plugin-styled-components/lib/visitors/pure.js' {
  declare module.exports: $Exports<'babel-plugin-styled-components/lib/visitors/pure'>;
}
declare module 'babel-plugin-styled-components/lib/visitors/templateLiterals/index.js' {
  declare module.exports: $Exports<'babel-plugin-styled-components/lib/visitors/templateLiterals/index'>;
}
declare module 'babel-plugin-styled-components/lib/visitors/templateLiterals/transpile.js' {
  declare module.exports: $Exports<'babel-plugin-styled-components/lib/visitors/templateLiterals/transpile'>;
}
declare module 'babel-plugin-styled-components/lib/visitors/transpileCssProp.js' {
  declare module.exports: $Exports<'babel-plugin-styled-components/lib/visitors/transpileCssProp'>;
}
