// flow-typed signature: e6263c15ef6789188b11afd5007f8d74
// flow-typed version: <<STUB>>/css-to-react-native_v^2.2.2/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-to-react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-to-react-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'css-to-react-native/src/__tests__/border' {
  declare module.exports: any;
}

declare module 'css-to-react-native/src/__tests__/borderColor' {
  declare module.exports: any;
}

declare module 'css-to-react-native/src/__tests__/boxModel' {
  declare module.exports: any;
}

declare module 'css-to-react-native/src/__tests__/boxShadow' {
  declare module.exports: any;
}

declare module 'css-to-react-native/src/__tests__/colors' {
  declare module.exports: any;
}

declare module 'css-to-react-native/src/__tests__/flex' {
  declare module.exports: any;
}

declare module 'css-to-react-native/src/__tests__/flexFlow' {
  declare module.exports: any;
}

declare module 'css-to-react-native/src/__tests__/font' {
  declare module.exports: any;
}

declare module 'css-to-react-native/src/__tests__/fontFamily' {
  declare module.exports: any;
}

declare module 'css-to-react-native/src/__tests__/fontVariant' {
  declare module.exports: any;
}

declare module 'css-to-react-native/src/__tests__/fontWeight' {
  declare module.exports: any;
}

declare module 'css-to-react-native/src/__tests__/index' {
  declare module.exports: any;
}

declare module 'css-to-react-native/src/__tests__/shadowOffsets' {
  declare module.exports: any;
}

declare module 'css-to-react-native/src/__tests__/textDecoration' {
  declare module.exports: any;
}

declare module 'css-to-react-native/src/__tests__/textDecorationLine' {
  declare module.exports: any;
}

declare module 'css-to-react-native/src/__tests__/textShadow' {
  declare module.exports: any;
}

declare module 'css-to-react-native/src/__tests__/transform' {
  declare module.exports: any;
}

declare module 'css-to-react-native/src/__tests__/units' {
  declare module.exports: any;
}

declare module 'css-to-react-native/src/index' {
  declare module.exports: any;
}

declare module 'css-to-react-native/src/TokenStream' {
  declare module.exports: any;
}

declare module 'css-to-react-native/src/tokenTypes' {
  declare module.exports: any;
}

declare module 'css-to-react-native/src/transforms/boxShadow' {
  declare module.exports: any;
}

declare module 'css-to-react-native/src/transforms/flex' {
  declare module.exports: any;
}

declare module 'css-to-react-native/src/transforms/font' {
  declare module.exports: any;
}

declare module 'css-to-react-native/src/transforms/fontFamily' {
  declare module.exports: any;
}

declare module 'css-to-react-native/src/transforms/index' {
  declare module.exports: any;
}

declare module 'css-to-react-native/src/transforms/textDecoration' {
  declare module.exports: any;
}

declare module 'css-to-react-native/src/transforms/textDecorationLine' {
  declare module.exports: any;
}

declare module 'css-to-react-native/src/transforms/textShadow' {
  declare module.exports: any;
}

declare module 'css-to-react-native/src/transforms/transform' {
  declare module.exports: any;
}

declare module 'css-to-react-native/src/transforms/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'css-to-react-native/index' {
  declare module.exports: $Exports<'css-to-react-native'>;
}
declare module 'css-to-react-native/index.js' {
  declare module.exports: $Exports<'css-to-react-native'>;
}
declare module 'css-to-react-native/src/__tests__/border.js' {
  declare module.exports: $Exports<'css-to-react-native/src/__tests__/border'>;
}
declare module 'css-to-react-native/src/__tests__/borderColor.js' {
  declare module.exports: $Exports<'css-to-react-native/src/__tests__/borderColor'>;
}
declare module 'css-to-react-native/src/__tests__/boxModel.js' {
  declare module.exports: $Exports<'css-to-react-native/src/__tests__/boxModel'>;
}
declare module 'css-to-react-native/src/__tests__/boxShadow.js' {
  declare module.exports: $Exports<'css-to-react-native/src/__tests__/boxShadow'>;
}
declare module 'css-to-react-native/src/__tests__/colors.js' {
  declare module.exports: $Exports<'css-to-react-native/src/__tests__/colors'>;
}
declare module 'css-to-react-native/src/__tests__/flex.js' {
  declare module.exports: $Exports<'css-to-react-native/src/__tests__/flex'>;
}
declare module 'css-to-react-native/src/__tests__/flexFlow.js' {
  declare module.exports: $Exports<'css-to-react-native/src/__tests__/flexFlow'>;
}
declare module 'css-to-react-native/src/__tests__/font.js' {
  declare module.exports: $Exports<'css-to-react-native/src/__tests__/font'>;
}
declare module 'css-to-react-native/src/__tests__/fontFamily.js' {
  declare module.exports: $Exports<'css-to-react-native/src/__tests__/fontFamily'>;
}
declare module 'css-to-react-native/src/__tests__/fontVariant.js' {
  declare module.exports: $Exports<'css-to-react-native/src/__tests__/fontVariant'>;
}
declare module 'css-to-react-native/src/__tests__/fontWeight.js' {
  declare module.exports: $Exports<'css-to-react-native/src/__tests__/fontWeight'>;
}
declare module 'css-to-react-native/src/__tests__/index.js' {
  declare module.exports: $Exports<'css-to-react-native/src/__tests__/index'>;
}
declare module 'css-to-react-native/src/__tests__/shadowOffsets.js' {
  declare module.exports: $Exports<'css-to-react-native/src/__tests__/shadowOffsets'>;
}
declare module 'css-to-react-native/src/__tests__/textDecoration.js' {
  declare module.exports: $Exports<'css-to-react-native/src/__tests__/textDecoration'>;
}
declare module 'css-to-react-native/src/__tests__/textDecorationLine.js' {
  declare module.exports: $Exports<'css-to-react-native/src/__tests__/textDecorationLine'>;
}
declare module 'css-to-react-native/src/__tests__/textShadow.js' {
  declare module.exports: $Exports<'css-to-react-native/src/__tests__/textShadow'>;
}
declare module 'css-to-react-native/src/__tests__/transform.js' {
  declare module.exports: $Exports<'css-to-react-native/src/__tests__/transform'>;
}
declare module 'css-to-react-native/src/__tests__/units.js' {
  declare module.exports: $Exports<'css-to-react-native/src/__tests__/units'>;
}
declare module 'css-to-react-native/src/index.js' {
  declare module.exports: $Exports<'css-to-react-native/src/index'>;
}
declare module 'css-to-react-native/src/TokenStream.js' {
  declare module.exports: $Exports<'css-to-react-native/src/TokenStream'>;
}
declare module 'css-to-react-native/src/tokenTypes.js' {
  declare module.exports: $Exports<'css-to-react-native/src/tokenTypes'>;
}
declare module 'css-to-react-native/src/transforms/boxShadow.js' {
  declare module.exports: $Exports<'css-to-react-native/src/transforms/boxShadow'>;
}
declare module 'css-to-react-native/src/transforms/flex.js' {
  declare module.exports: $Exports<'css-to-react-native/src/transforms/flex'>;
}
declare module 'css-to-react-native/src/transforms/font.js' {
  declare module.exports: $Exports<'css-to-react-native/src/transforms/font'>;
}
declare module 'css-to-react-native/src/transforms/fontFamily.js' {
  declare module.exports: $Exports<'css-to-react-native/src/transforms/fontFamily'>;
}
declare module 'css-to-react-native/src/transforms/index.js' {
  declare module.exports: $Exports<'css-to-react-native/src/transforms/index'>;
}
declare module 'css-to-react-native/src/transforms/textDecoration.js' {
  declare module.exports: $Exports<'css-to-react-native/src/transforms/textDecoration'>;
}
declare module 'css-to-react-native/src/transforms/textDecorationLine.js' {
  declare module.exports: $Exports<'css-to-react-native/src/transforms/textDecorationLine'>;
}
declare module 'css-to-react-native/src/transforms/textShadow.js' {
  declare module.exports: $Exports<'css-to-react-native/src/transforms/textShadow'>;
}
declare module 'css-to-react-native/src/transforms/transform.js' {
  declare module.exports: $Exports<'css-to-react-native/src/transforms/transform'>;
}
declare module 'css-to-react-native/src/transforms/util.js' {
  declare module.exports: $Exports<'css-to-react-native/src/transforms/util'>;
}
