// flow-typed signature: e7758ca1251748d9cb57509ae99126e8
// flow-typed version: <<STUB>>/css-to-react-native_v^1.0.6/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-to-react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-to-react-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'css-to-react-native/dist/grammar' {
  declare module.exports: any;
}

declare module 'css-to-react-native/dist/index' {
  declare module.exports: any;
}

declare module 'css-to-react-native/src/index' {
  declare module.exports: any;
}

declare module 'css-to-react-native/src/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'css-to-react-native/dist/grammar.js' {
  declare module.exports: $Exports<'css-to-react-native/dist/grammar'>;
}
declare module 'css-to-react-native/dist/index.js' {
  declare module.exports: $Exports<'css-to-react-native/dist/index'>;
}
declare module 'css-to-react-native/src/index.js' {
  declare module.exports: $Exports<'css-to-react-native/src/index'>;
}
declare module 'css-to-react-native/src/index.test.js' {
  declare module.exports: $Exports<'css-to-react-native/src/index.test'>;
}
