// flow-typed signature: 77381145f324bdeeacbb2f4c7a85672d
// flow-typed version: <<STUB>>/danger-plugin-jest_v^1.1.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'danger-plugin-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'danger-plugin-jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'danger-plugin-jest/dist/index' {
  declare module.exports: any;
}

declare module 'danger-plugin-jest/dist/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'danger-plugin-jest/dist/index.js' {
  declare module.exports: $Exports<'danger-plugin-jest/dist/index'>;
}
declare module 'danger-plugin-jest/dist/types.js' {
  declare module.exports: $Exports<'danger-plugin-jest/dist/types'>;
}
