// flow-typed signature: 6a7f7ba47ad5dbc490f85494cd7f2fdf
// flow-typed version: <<STUB>>/danger_v^0.9.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'danger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'danger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'danger/distribution/api/fetch' {
  declare module.exports: any;
}

declare module 'danger/distribution/ci_source/ci_source_helpers' {
  declare module.exports: any;
}

declare module 'danger/distribution/ci_source/ci_source_selector' {
  declare module.exports: any;
}

declare module 'danger/distribution/ci_source/ci_source' {
  declare module.exports: any;
}

declare module 'danger/distribution/ci_source/get_ci_source' {
  declare module.exports: any;
}

declare module 'danger/distribution/ci_source/providers/Circle' {
  declare module.exports: any;
}

declare module 'danger/distribution/ci_source/providers/Fake' {
  declare module.exports: any;
}

declare module 'danger/distribution/ci_source/providers/index' {
  declare module.exports: any;
}

declare module 'danger/distribution/ci_source/providers/Jenkins' {
  declare module.exports: any;
}

declare module 'danger/distribution/ci_source/providers/Semaphore' {
  declare module.exports: any;
}

declare module 'danger/distribution/ci_source/providers/Surf' {
  declare module.exports: any;
}

declare module 'danger/distribution/ci_source/providers/Travis' {
  declare module.exports: any;
}

declare module 'danger/distribution/commands/danger-local' {
  declare module.exports: any;
}

declare module 'danger/distribution/commands/danger-pr' {
  declare module.exports: any;
}

declare module 'danger/distribution/commands/danger-run' {
  declare module.exports: any;
}

declare module 'danger/distribution/commands/danger' {
  declare module.exports: any;
}

declare module 'danger/distribution/danger' {
  declare module.exports: any;
}

declare module 'danger/distribution/dsl/Aliases' {
  declare module.exports: any;
}

declare module 'danger/distribution/dsl/Commit' {
  declare module.exports: any;
}

declare module 'danger/distribution/dsl/DangerDSL' {
  declare module.exports: any;
}

declare module 'danger/distribution/dsl/DangerResults' {
  declare module.exports: any;
}

declare module 'danger/distribution/dsl/GitDSL' {
  declare module.exports: any;
}

declare module 'danger/distribution/dsl/GitHubDSL' {
  declare module.exports: any;
}

declare module 'danger/distribution/platforms/FakePlatform' {
  declare module.exports: any;
}

declare module 'danger/distribution/platforms/GitHub' {
  declare module.exports: any;
}

declare module 'danger/distribution/platforms/messaging/violation' {
  declare module.exports: any;
}

declare module 'danger/distribution/platforms/platform' {
  declare module.exports: any;
}

declare module 'danger/distribution/runner/Dangerfile' {
  declare module.exports: any;
}

declare module 'danger/distribution/runner/DangerfileRunner' {
  declare module.exports: any;
}

declare module 'danger/distribution/runner/Executor' {
  declare module.exports: any;
}

declare module 'danger/distribution/runner/templates/github-issue-template' {
  declare module.exports: any;
}

declare module 'danger/distribution/runner/types' {
  declare module.exports: any;
}

declare module 'danger/wallaby' {
  declare module.exports: any;
}

// Filename aliases
declare module 'danger/distribution/api/fetch.js' {
  declare module.exports: $Exports<'danger/distribution/api/fetch'>;
}
declare module 'danger/distribution/ci_source/ci_source_helpers.js' {
  declare module.exports: $Exports<'danger/distribution/ci_source/ci_source_helpers'>;
}
declare module 'danger/distribution/ci_source/ci_source_selector.js' {
  declare module.exports: $Exports<'danger/distribution/ci_source/ci_source_selector'>;
}
declare module 'danger/distribution/ci_source/ci_source.js' {
  declare module.exports: $Exports<'danger/distribution/ci_source/ci_source'>;
}
declare module 'danger/distribution/ci_source/get_ci_source.js' {
  declare module.exports: $Exports<'danger/distribution/ci_source/get_ci_source'>;
}
declare module 'danger/distribution/ci_source/providers/Circle.js' {
  declare module.exports: $Exports<'danger/distribution/ci_source/providers/Circle'>;
}
declare module 'danger/distribution/ci_source/providers/Fake.js' {
  declare module.exports: $Exports<'danger/distribution/ci_source/providers/Fake'>;
}
declare module 'danger/distribution/ci_source/providers/index.js' {
  declare module.exports: $Exports<'danger/distribution/ci_source/providers/index'>;
}
declare module 'danger/distribution/ci_source/providers/Jenkins.js' {
  declare module.exports: $Exports<'danger/distribution/ci_source/providers/Jenkins'>;
}
declare module 'danger/distribution/ci_source/providers/Semaphore.js' {
  declare module.exports: $Exports<'danger/distribution/ci_source/providers/Semaphore'>;
}
declare module 'danger/distribution/ci_source/providers/Surf.js' {
  declare module.exports: $Exports<'danger/distribution/ci_source/providers/Surf'>;
}
declare module 'danger/distribution/ci_source/providers/Travis.js' {
  declare module.exports: $Exports<'danger/distribution/ci_source/providers/Travis'>;
}
declare module 'danger/distribution/commands/danger-local.js' {
  declare module.exports: $Exports<'danger/distribution/commands/danger-local'>;
}
declare module 'danger/distribution/commands/danger-pr.js' {
  declare module.exports: $Exports<'danger/distribution/commands/danger-pr'>;
}
declare module 'danger/distribution/commands/danger-run.js' {
  declare module.exports: $Exports<'danger/distribution/commands/danger-run'>;
}
declare module 'danger/distribution/commands/danger.js' {
  declare module.exports: $Exports<'danger/distribution/commands/danger'>;
}
declare module 'danger/distribution/danger.js' {
  declare module.exports: $Exports<'danger/distribution/danger'>;
}
declare module 'danger/distribution/dsl/Aliases.js' {
  declare module.exports: $Exports<'danger/distribution/dsl/Aliases'>;
}
declare module 'danger/distribution/dsl/Commit.js' {
  declare module.exports: $Exports<'danger/distribution/dsl/Commit'>;
}
declare module 'danger/distribution/dsl/DangerDSL.js' {
  declare module.exports: $Exports<'danger/distribution/dsl/DangerDSL'>;
}
declare module 'danger/distribution/dsl/DangerResults.js' {
  declare module.exports: $Exports<'danger/distribution/dsl/DangerResults'>;
}
declare module 'danger/distribution/dsl/GitDSL.js' {
  declare module.exports: $Exports<'danger/distribution/dsl/GitDSL'>;
}
declare module 'danger/distribution/dsl/GitHubDSL.js' {
  declare module.exports: $Exports<'danger/distribution/dsl/GitHubDSL'>;
}
declare module 'danger/distribution/platforms/FakePlatform.js' {
  declare module.exports: $Exports<'danger/distribution/platforms/FakePlatform'>;
}
declare module 'danger/distribution/platforms/GitHub.js' {
  declare module.exports: $Exports<'danger/distribution/platforms/GitHub'>;
}
declare module 'danger/distribution/platforms/messaging/violation.js' {
  declare module.exports: $Exports<'danger/distribution/platforms/messaging/violation'>;
}
declare module 'danger/distribution/platforms/platform.js' {
  declare module.exports: $Exports<'danger/distribution/platforms/platform'>;
}
declare module 'danger/distribution/runner/Dangerfile.js' {
  declare module.exports: $Exports<'danger/distribution/runner/Dangerfile'>;
}
declare module 'danger/distribution/runner/DangerfileRunner.js' {
  declare module.exports: $Exports<'danger/distribution/runner/DangerfileRunner'>;
}
declare module 'danger/distribution/runner/Executor.js' {
  declare module.exports: $Exports<'danger/distribution/runner/Executor'>;
}
declare module 'danger/distribution/runner/templates/github-issue-template.js' {
  declare module.exports: $Exports<'danger/distribution/runner/templates/github-issue-template'>;
}
declare module 'danger/distribution/runner/types.js' {
  declare module.exports: $Exports<'danger/distribution/runner/types'>;
}
declare module 'danger/wallaby.js' {
  declare module.exports: $Exports<'danger/wallaby'>;
}
