// flow-typed signature: d77b997468783db026a23e0e5c27aec2
// flow-typed version: <<STUB>>/flow-watch_v^2.0.0/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-watch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-watch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow-watch/createNodemonArgs' {
  declare module.exports: any;
}

declare module 'flow-watch/runFlow' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flow-watch/createNodemonArgs.js' {
  declare module.exports: $Exports<'flow-watch/createNodemonArgs'>;
}
declare module 'flow-watch/index' {
  declare module.exports: $Exports<'flow-watch'>;
}
declare module 'flow-watch/index.js' {
  declare module.exports: $Exports<'flow-watch'>;
}
declare module 'flow-watch/runFlow.js' {
  declare module.exports: $Exports<'flow-watch/runFlow'>;
}
