// flow-typed signature: 20b29f64dec1f0ec7e28e399b98da948
// flow-typed version: <<STUB>>/hoist-non-react-statics_v2.5.5/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hoist-non-react-statics'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hoist-non-react-statics' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hoist-non-react-statics/dist/hoist-non-react-statics.cjs' {
  declare module.exports: any;
}

declare module 'hoist-non-react-statics/dist/hoist-non-react-statics' {
  declare module.exports: any;
}

declare module 'hoist-non-react-statics/dist/hoist-non-react-statics.min' {
  declare module.exports: any;
}

declare module 'hoist-non-react-statics/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hoist-non-react-statics/dist/hoist-non-react-statics.cjs.js' {
  declare module.exports: $Exports<'hoist-non-react-statics/dist/hoist-non-react-statics.cjs'>;
}
declare module 'hoist-non-react-statics/dist/hoist-non-react-statics.js' {
  declare module.exports: $Exports<'hoist-non-react-statics/dist/hoist-non-react-statics'>;
}
declare module 'hoist-non-react-statics/dist/hoist-non-react-statics.min.js' {
  declare module.exports: $Exports<'hoist-non-react-statics/dist/hoist-non-react-statics.min'>;
}
declare module 'hoist-non-react-statics/src/index.js' {
  declare module.exports: $Exports<'hoist-non-react-statics/src/index'>;
}
