// flow-typed signature: a2242dc27fc55181cc075cb231adb2d4
// flow-typed version: <<STUB>>/inline-style-prefixer_v^2.0.5/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inline-style-prefixer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'inline-style-prefixer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inline-style-prefixer/dist/inline-style-prefix-all' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/dist/inline-style-prefix-all.min' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/dist/inline-style-prefixer' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/dist/inline-style-prefixer.min' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/plugins/calc' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/plugins/flex' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/plugins/flexboxIE' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/plugins/flexboxOld' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/plugins/grabCursor' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/plugins/gradient' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/plugins/position' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/plugins/sizing' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/plugins/transition' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/plugins/zoomCursor' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/Prefixer' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/prefixProps' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/static/plugins/calc' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/static/plugins/cursor' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/static/plugins/flex' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/static/plugins/flexboxIE' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/static/plugins/flexboxOld' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/static/plugins/gradient' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/static/plugins/position' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/static/plugins/sizing' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/static/plugins/transition' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/static/prefixAll' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/static/prefixProps' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/utils/capitalizeString' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/utils/getBrowserInformation' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/utils/getPrefixedKeyframes' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/utils/getPrefixedValue' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/utils/isPrefixedProperty' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/utils/isPrefixedValue' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/utils/joinPrefixedValue' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/utils/sortPrefixedStyle' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/lib/utils/unprefixProperty' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/static' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inline-style-prefixer/dist/inline-style-prefix-all.js' {
  declare module.exports: $Exports<'inline-style-prefixer/dist/inline-style-prefix-all'>;
}
declare module 'inline-style-prefixer/dist/inline-style-prefix-all.min.js' {
  declare module.exports: $Exports<'inline-style-prefixer/dist/inline-style-prefix-all.min'>;
}
declare module 'inline-style-prefixer/dist/inline-style-prefixer.js' {
  declare module.exports: $Exports<'inline-style-prefixer/dist/inline-style-prefixer'>;
}
declare module 'inline-style-prefixer/dist/inline-style-prefixer.min.js' {
  declare module.exports: $Exports<'inline-style-prefixer/dist/inline-style-prefixer.min'>;
}
declare module 'inline-style-prefixer/lib/plugins/calc.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/plugins/calc'>;
}
declare module 'inline-style-prefixer/lib/plugins/flex.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/plugins/flex'>;
}
declare module 'inline-style-prefixer/lib/plugins/flexboxIE.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/plugins/flexboxIE'>;
}
declare module 'inline-style-prefixer/lib/plugins/flexboxOld.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/plugins/flexboxOld'>;
}
declare module 'inline-style-prefixer/lib/plugins/grabCursor.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/plugins/grabCursor'>;
}
declare module 'inline-style-prefixer/lib/plugins/gradient.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/plugins/gradient'>;
}
declare module 'inline-style-prefixer/lib/plugins/position.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/plugins/position'>;
}
declare module 'inline-style-prefixer/lib/plugins/sizing.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/plugins/sizing'>;
}
declare module 'inline-style-prefixer/lib/plugins/transition.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/plugins/transition'>;
}
declare module 'inline-style-prefixer/lib/plugins/zoomCursor.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/plugins/zoomCursor'>;
}
declare module 'inline-style-prefixer/lib/Prefixer.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/Prefixer'>;
}
declare module 'inline-style-prefixer/lib/prefixProps.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/prefixProps'>;
}
declare module 'inline-style-prefixer/lib/static/plugins/calc.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/static/plugins/calc'>;
}
declare module 'inline-style-prefixer/lib/static/plugins/cursor.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/static/plugins/cursor'>;
}
declare module 'inline-style-prefixer/lib/static/plugins/flex.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/static/plugins/flex'>;
}
declare module 'inline-style-prefixer/lib/static/plugins/flexboxIE.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/static/plugins/flexboxIE'>;
}
declare module 'inline-style-prefixer/lib/static/plugins/flexboxOld.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/static/plugins/flexboxOld'>;
}
declare module 'inline-style-prefixer/lib/static/plugins/gradient.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/static/plugins/gradient'>;
}
declare module 'inline-style-prefixer/lib/static/plugins/position.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/static/plugins/position'>;
}
declare module 'inline-style-prefixer/lib/static/plugins/sizing.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/static/plugins/sizing'>;
}
declare module 'inline-style-prefixer/lib/static/plugins/transition.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/static/plugins/transition'>;
}
declare module 'inline-style-prefixer/lib/static/prefixAll.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/static/prefixAll'>;
}
declare module 'inline-style-prefixer/lib/static/prefixProps.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/static/prefixProps'>;
}
declare module 'inline-style-prefixer/lib/utils/capitalizeString.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/utils/capitalizeString'>;
}
declare module 'inline-style-prefixer/lib/utils/getBrowserInformation.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/utils/getBrowserInformation'>;
}
declare module 'inline-style-prefixer/lib/utils/getPrefixedKeyframes.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/utils/getPrefixedKeyframes'>;
}
declare module 'inline-style-prefixer/lib/utils/getPrefixedValue.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/utils/getPrefixedValue'>;
}
declare module 'inline-style-prefixer/lib/utils/isPrefixedProperty.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/utils/isPrefixedProperty'>;
}
declare module 'inline-style-prefixer/lib/utils/isPrefixedValue.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/utils/isPrefixedValue'>;
}
declare module 'inline-style-prefixer/lib/utils/joinPrefixedValue.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/utils/joinPrefixedValue'>;
}
declare module 'inline-style-prefixer/lib/utils/sortPrefixedStyle.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/utils/sortPrefixedStyle'>;
}
declare module 'inline-style-prefixer/lib/utils/unprefixProperty.js' {
  declare module.exports: $Exports<'inline-style-prefixer/lib/utils/unprefixProperty'>;
}
declare module 'inline-style-prefixer/static.js' {
  declare module.exports: $Exports<'inline-style-prefixer/static'>;
}
