// flow-typed signature: f6b9b84b7edfde941d7c559f2f4681f5
// flow-typed version: <<STUB>>/invariant_v2.2.2/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'invariant'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'invariant' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'invariant/browser' {
  declare module.exports: any;
}

declare module 'invariant/invariant' {
  declare module.exports: any;
}

// Filename aliases
declare module 'invariant/browser.js' {
  declare module.exports: $Exports<'invariant/browser'>;
}
declare module 'invariant/invariant.js' {
  declare module.exports: $Exports<'invariant/invariant'>;
}
