// flow-typed signature: f087ac7f75c3cd1ca8d366bdbb69e804
// flow-typed version: <<STUB>>/is-function_v^1.0.1/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-function'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-function' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'is-function/browser-test' {
  declare module.exports: any;
}

declare module 'is-function/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'is-function/browser-test.js' {
  declare module.exports: $Exports<'is-function/browser-test'>;
}
declare module 'is-function/index' {
  declare module.exports: $Exports<'is-function'>;
}
declare module 'is-function/index.js' {
  declare module.exports: $Exports<'is-function'>;
}
declare module 'is-function/test.js' {
  declare module.exports: $Exports<'is-function/test'>;
}
