// flow-typed signature: 80594aa906306cf19492e57892bcbb7d
// flow-typed version: <<STUB>>/is-plain-object_v^2.0.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-plain-object'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-plain-object' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'is-plain-object/index' {
  declare module.exports: $Exports<'is-plain-object'>;
}
declare module 'is-plain-object/index.js' {
  declare module.exports: $Exports<'is-plain-object'>;
}
