// flow-typed signature: 8b7dcdda7ce040b28b495fc335c77141
// flow-typed version: <<STUB>>/is-react-prop_v0.0.2/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-react-prop'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-react-prop' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'is-react-prop/lib/index' {
  declare module.exports: any;
}

declare module 'is-react-prop/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'is-react-prop/lib/index.js' {
  declare module.exports: $Exports<'is-react-prop/lib/index'>;
}
declare module 'is-react-prop/src/index.js' {
  declare module.exports: $Exports<'is-react-prop/src/index'>;
}
