// flow-typed signature: 1c46cd991cba8d6e5e2e5c90637dc420
// flow-typed version: <<STUB>>/jest-image-snapshot_v^2.8.1/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-image-snapshot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-image-snapshot' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-image-snapshot/src/diff-process' {
  declare module.exports: any;
}

declare module 'jest-image-snapshot/src/diff-snapshot' {
  declare module.exports: any;
}

declare module 'jest-image-snapshot/src/image-composer' {
  declare module.exports: any;
}

declare module 'jest-image-snapshot/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-image-snapshot/src/diff-process.js' {
  declare module.exports: $Exports<'jest-image-snapshot/src/diff-process'>;
}
declare module 'jest-image-snapshot/src/diff-snapshot.js' {
  declare module.exports: $Exports<'jest-image-snapshot/src/diff-snapshot'>;
}
declare module 'jest-image-snapshot/src/image-composer.js' {
  declare module.exports: $Exports<'jest-image-snapshot/src/image-composer'>;
}
declare module 'jest-image-snapshot/src/index' {
  declare module.exports: $Exports<'jest-image-snapshot/src'>;
}
declare module 'jest-image-snapshot/src/index.js' {
  declare module.exports: $Exports<'jest-image-snapshot/src'>;
}
