// flow-typed signature: 467f96db5564af5066e2654bdb972531
// flow-typed version: <<STUB>>/lint-staged_v^3.0.3/flow_v0.32.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lint-staged'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'lint-staged' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lint-staged/src/findBin' {
  declare module.exports: any;
}

declare module 'lint-staged/src/index' {
  declare module.exports: any;
}

declare module 'lint-staged/src/runScript' {
  declare module.exports: any;
}

declare module 'lint-staged/test/findBin.spec' {
  declare module.exports: any;
}

declare module 'lint-staged/test/runScript.spec' {
  declare module.exports: any;
}

declare module 'lint-staged/wallaby' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lint-staged/index' {
  declare module.exports: $Exports<'lint-staged'>;
}
declare module 'lint-staged/index.js' {
  declare module.exports: $Exports<'lint-staged'>;
}
declare module 'lint-staged/src/findBin.js' {
  declare module.exports: $Exports<'lint-staged/src/findBin'>;
}
declare module 'lint-staged/src/index.js' {
  declare module.exports: $Exports<'lint-staged/src/index'>;
}
declare module 'lint-staged/src/runScript.js' {
  declare module.exports: $Exports<'lint-staged/src/runScript'>;
}
declare module 'lint-staged/test/findBin.spec.js' {
  declare module.exports: $Exports<'lint-staged/test/findBin.spec'>;
}
declare module 'lint-staged/test/runScript.spec.js' {
  declare module.exports: $Exports<'lint-staged/test/runScript.spec'>;
}
declare module 'lint-staged/wallaby.js' {
  declare module.exports: $Exports<'lint-staged/wallaby'>;
}
