// @flow
// flow-typed signature: b6875562f230d378cdab0b00bcdbf926
// flow-typed version: <<STUB>>/memoize-one_v4.0.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'memoize-one'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'memoize-one' {
  declare module.exports: any
}
