// flow-typed signature: 22b669b67c755745dff603ec784dc0c8
// flow-typed version: <<STUB>>/merge-anything_v^2.2.5/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'merge-anything'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'merge-anything' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'merge-anything/build/rollup' {
  declare module.exports: any;
}

declare module 'merge-anything/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'merge-anything/dist/index.esm' {
  declare module.exports: any;
}

declare module 'merge-anything/test/index' {
  declare module.exports: any;
}

declare module 'merge-anything/wallaby.conf' {
  declare module.exports: any;
}

// Filename aliases
declare module 'merge-anything/build/rollup.js' {
  declare module.exports: $Exports<'merge-anything/build/rollup'>;
}
declare module 'merge-anything/dist/index.cjs.js' {
  declare module.exports: $Exports<'merge-anything/dist/index.cjs'>;
}
declare module 'merge-anything/dist/index.esm.js' {
  declare module.exports: $Exports<'merge-anything/dist/index.esm'>;
}
declare module 'merge-anything/test/index.js' {
  declare module.exports: $Exports<'merge-anything/test/index'>;
}
declare module 'merge-anything/wallaby.conf.js' {
  declare module.exports: $Exports<'merge-anything/wallaby.conf'>;
}
