// flow-typed signature: da2b5df44c1b606a49f651a0d9902a9f
// flow-typed version: <<STUB>>/mocha-jsdom_v^1.1.0/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mocha-jsdom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mocha-jsdom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mocha-jsdom/browser' {
  declare module.exports: any;
}

declare module 'mocha-jsdom/examples/basic/setup' {
  declare module.exports: any;
}

declare module 'mocha-jsdom/examples/basic/test' {
  declare module.exports: any;
}

declare module 'mocha-jsdom/examples/failures/one' {
  declare module.exports: any;
}

declare module 'mocha-jsdom/examples/failures/two' {
  declare module.exports: any;
}

declare module 'mocha-jsdom/test/fixtures/rerequirable' {
  declare module.exports: any;
}

declare module 'mocha-jsdom/test/globalize' {
  declare module.exports: any;
}

declare module 'mocha-jsdom/test/jquery' {
  declare module.exports: any;
}

declare module 'mocha-jsdom/test/rerequire_test' {
  declare module.exports: any;
}

declare module 'mocha-jsdom/test/robust' {
  declare module.exports: any;
}

declare module 'mocha-jsdom/test/setup' {
  declare module.exports: any;
}

declare module 'mocha-jsdom/test/simple' {
  declare module.exports: any;
}

declare module 'mocha-jsdom/test/skip_window_check' {
  declare module.exports: any;
}

declare module 'mocha-jsdom/test/standard_test' {
  declare module.exports: any;
}

declare module 'mocha-jsdom/test/use_each' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mocha-jsdom/browser.js' {
  declare module.exports: $Exports<'mocha-jsdom/browser'>;
}
declare module 'mocha-jsdom/examples/basic/setup.js' {
  declare module.exports: $Exports<'mocha-jsdom/examples/basic/setup'>;
}
declare module 'mocha-jsdom/examples/basic/test.js' {
  declare module.exports: $Exports<'mocha-jsdom/examples/basic/test'>;
}
declare module 'mocha-jsdom/examples/failures/one.js' {
  declare module.exports: $Exports<'mocha-jsdom/examples/failures/one'>;
}
declare module 'mocha-jsdom/examples/failures/two.js' {
  declare module.exports: $Exports<'mocha-jsdom/examples/failures/two'>;
}
declare module 'mocha-jsdom/index' {
  declare module.exports: $Exports<'mocha-jsdom'>;
}
declare module 'mocha-jsdom/index.js' {
  declare module.exports: $Exports<'mocha-jsdom'>;
}
declare module 'mocha-jsdom/test/fixtures/rerequirable.js' {
  declare module.exports: $Exports<'mocha-jsdom/test/fixtures/rerequirable'>;
}
declare module 'mocha-jsdom/test/globalize.js' {
  declare module.exports: $Exports<'mocha-jsdom/test/globalize'>;
}
declare module 'mocha-jsdom/test/jquery.js' {
  declare module.exports: $Exports<'mocha-jsdom/test/jquery'>;
}
declare module 'mocha-jsdom/test/rerequire_test.js' {
  declare module.exports: $Exports<'mocha-jsdom/test/rerequire_test'>;
}
declare module 'mocha-jsdom/test/robust.js' {
  declare module.exports: $Exports<'mocha-jsdom/test/robust'>;
}
declare module 'mocha-jsdom/test/setup.js' {
  declare module.exports: $Exports<'mocha-jsdom/test/setup'>;
}
declare module 'mocha-jsdom/test/simple.js' {
  declare module.exports: $Exports<'mocha-jsdom/test/simple'>;
}
declare module 'mocha-jsdom/test/skip_window_check.js' {
  declare module.exports: $Exports<'mocha-jsdom/test/skip_window_check'>;
}
declare module 'mocha-jsdom/test/standard_test.js' {
  declare module.exports: $Exports<'mocha-jsdom/test/standard_test'>;
}
declare module 'mocha-jsdom/test/use_each.js' {
  declare module.exports: $Exports<'mocha-jsdom/test/use_each'>;
}
