// flow-typed signature: 882194d91554cedc0fed8c667eab6ca0
// flow-typed version: <<STUB>>/node-watch_v^0.4.1/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-watch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-watch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-watch/lib/watch' {
  declare module.exports: any;
}

declare module 'node-watch/test/filter-option' {
  declare module.exports: any;
}

declare module 'node-watch/test/utils/tree' {
  declare module.exports: any;
}

declare module 'node-watch/test/watcher' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-watch/index' {
  declare module.exports: $Exports<'node-watch'>;
}
declare module 'node-watch/index.js' {
  declare module.exports: $Exports<'node-watch'>;
}
declare module 'node-watch/lib/watch.js' {
  declare module.exports: $Exports<'node-watch/lib/watch'>;
}
declare module 'node-watch/test/filter-option.js' {
  declare module.exports: $Exports<'node-watch/test/filter-option'>;
}
declare module 'node-watch/test/utils/tree.js' {
  declare module.exports: $Exports<'node-watch/test/utils/tree'>;
}
declare module 'node-watch/test/watcher.js' {
  declare module.exports: $Exports<'node-watch/test/watcher'>;
}
