// flow-typed signature: 8f383b92fdda3052ddf7075a15da712e
// flow-typed version: <<STUB>>/node-watch_v^0.5.0/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-watch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-watch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-watch/lib/has-native-recursive' {
  declare module.exports: any;
}

declare module 'node-watch/lib/is' {
  declare module.exports: any;
}

declare module 'node-watch/lib/watch' {
  declare module.exports: any;
}

declare module 'node-watch/test/test' {
  declare module.exports: any;
}

declare module 'node-watch/test/utils/builder' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-watch/index' {
  declare module.exports: $Exports<'node-watch'>;
}
declare module 'node-watch/index.js' {
  declare module.exports: $Exports<'node-watch'>;
}
declare module 'node-watch/lib/has-native-recursive.js' {
  declare module.exports: $Exports<'node-watch/lib/has-native-recursive'>;
}
declare module 'node-watch/lib/is.js' {
  declare module.exports: $Exports<'node-watch/lib/is'>;
}
declare module 'node-watch/lib/watch.js' {
  declare module.exports: $Exports<'node-watch/lib/watch'>;
}
declare module 'node-watch/test/test.js' {
  declare module.exports: $Exports<'node-watch/test/test'>;
}
declare module 'node-watch/test/utils/builder.js' {
  declare module.exports: $Exports<'node-watch/test/utils/builder'>;
}
