// flow-typed signature: 40bb3da98850f14c37b3fd46a0265e8e
// flow-typed version: <<STUB>>/npm-run-all_v^4.1.2/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npm-run-all'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'npm-run-all' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'npm-run-all/bin/common/bootstrap' {
  declare module.exports: any;
}

declare module 'npm-run-all/bin/common/parse-cli-args' {
  declare module.exports: any;
}

declare module 'npm-run-all/bin/common/version' {
  declare module.exports: any;
}

declare module 'npm-run-all/bin/npm-run-all/help' {
  declare module.exports: any;
}

declare module 'npm-run-all/bin/npm-run-all/index' {
  declare module.exports: any;
}

declare module 'npm-run-all/bin/npm-run-all/main' {
  declare module.exports: any;
}

declare module 'npm-run-all/bin/run-p/help' {
  declare module.exports: any;
}

declare module 'npm-run-all/bin/run-p/index' {
  declare module.exports: any;
}

declare module 'npm-run-all/bin/run-p/main' {
  declare module.exports: any;
}

declare module 'npm-run-all/bin/run-s/help' {
  declare module.exports: any;
}

declare module 'npm-run-all/bin/run-s/index' {
  declare module.exports: any;
}

declare module 'npm-run-all/bin/run-s/main' {
  declare module.exports: any;
}

declare module 'npm-run-all/lib/create-header' {
  declare module.exports: any;
}

declare module 'npm-run-all/lib/create-prefix-transform-stream' {
  declare module.exports: any;
}

declare module 'npm-run-all/lib/index' {
  declare module.exports: any;
}

declare module 'npm-run-all/lib/match-tasks' {
  declare module.exports: any;
}

declare module 'npm-run-all/lib/npm-run-all-error' {
  declare module.exports: any;
}

declare module 'npm-run-all/lib/read-package-json' {
  declare module.exports: any;
}

declare module 'npm-run-all/lib/run-task' {
  declare module.exports: any;
}

declare module 'npm-run-all/lib/run-tasks' {
  declare module.exports: any;
}

declare module 'npm-run-all/lib/spawn-posix' {
  declare module.exports: any;
}

declare module 'npm-run-all/lib/spawn-win32' {
  declare module.exports: any;
}

declare module 'npm-run-all/lib/spawn' {
  declare module.exports: any;
}

// Filename aliases
declare module 'npm-run-all/bin/common/bootstrap.js' {
  declare module.exports: $Exports<'npm-run-all/bin/common/bootstrap'>;
}
declare module 'npm-run-all/bin/common/parse-cli-args.js' {
  declare module.exports: $Exports<'npm-run-all/bin/common/parse-cli-args'>;
}
declare module 'npm-run-all/bin/common/version.js' {
  declare module.exports: $Exports<'npm-run-all/bin/common/version'>;
}
declare module 'npm-run-all/bin/npm-run-all/help.js' {
  declare module.exports: $Exports<'npm-run-all/bin/npm-run-all/help'>;
}
declare module 'npm-run-all/bin/npm-run-all/index.js' {
  declare module.exports: $Exports<'npm-run-all/bin/npm-run-all/index'>;
}
declare module 'npm-run-all/bin/npm-run-all/main.js' {
  declare module.exports: $Exports<'npm-run-all/bin/npm-run-all/main'>;
}
declare module 'npm-run-all/bin/run-p/help.js' {
  declare module.exports: $Exports<'npm-run-all/bin/run-p/help'>;
}
declare module 'npm-run-all/bin/run-p/index.js' {
  declare module.exports: $Exports<'npm-run-all/bin/run-p/index'>;
}
declare module 'npm-run-all/bin/run-p/main.js' {
  declare module.exports: $Exports<'npm-run-all/bin/run-p/main'>;
}
declare module 'npm-run-all/bin/run-s/help.js' {
  declare module.exports: $Exports<'npm-run-all/bin/run-s/help'>;
}
declare module 'npm-run-all/bin/run-s/index.js' {
  declare module.exports: $Exports<'npm-run-all/bin/run-s/index'>;
}
declare module 'npm-run-all/bin/run-s/main.js' {
  declare module.exports: $Exports<'npm-run-all/bin/run-s/main'>;
}
declare module 'npm-run-all/lib/create-header.js' {
  declare module.exports: $Exports<'npm-run-all/lib/create-header'>;
}
declare module 'npm-run-all/lib/create-prefix-transform-stream.js' {
  declare module.exports: $Exports<'npm-run-all/lib/create-prefix-transform-stream'>;
}
declare module 'npm-run-all/lib/index.js' {
  declare module.exports: $Exports<'npm-run-all/lib/index'>;
}
declare module 'npm-run-all/lib/match-tasks.js' {
  declare module.exports: $Exports<'npm-run-all/lib/match-tasks'>;
}
declare module 'npm-run-all/lib/npm-run-all-error.js' {
  declare module.exports: $Exports<'npm-run-all/lib/npm-run-all-error'>;
}
declare module 'npm-run-all/lib/read-package-json.js' {
  declare module.exports: $Exports<'npm-run-all/lib/read-package-json'>;
}
declare module 'npm-run-all/lib/run-task.js' {
  declare module.exports: $Exports<'npm-run-all/lib/run-task'>;
}
declare module 'npm-run-all/lib/run-tasks.js' {
  declare module.exports: $Exports<'npm-run-all/lib/run-tasks'>;
}
declare module 'npm-run-all/lib/spawn-posix.js' {
  declare module.exports: $Exports<'npm-run-all/lib/spawn-posix'>;
}
declare module 'npm-run-all/lib/spawn-win32.js' {
  declare module.exports: $Exports<'npm-run-all/lib/spawn-win32'>;
}
declare module 'npm-run-all/lib/spawn.js' {
  declare module.exports: $Exports<'npm-run-all/lib/spawn'>;
}
