// flow-typed signature: b0e7ab49671c0c812975f3adf83292f3
// flow-typed version: <<STUB>>/pre-commit_v^1.2.2/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pre-commit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'pre-commit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pre-commit/install' {
  declare module.exports: any;
}

declare module 'pre-commit/test' {
  declare module.exports: any;
}

declare module 'pre-commit/uninstall' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pre-commit/index' {
  declare module.exports: $Exports<'pre-commit'>;
}
declare module 'pre-commit/index.js' {
  declare module.exports: $Exports<'pre-commit'>;
}
declare module 'pre-commit/install.js' {
  declare module.exports: $Exports<'pre-commit/install'>;
}
declare module 'pre-commit/test.js' {
  declare module.exports: $Exports<'pre-commit/test'>;
}
declare module 'pre-commit/uninstall.js' {
  declare module.exports: $Exports<'pre-commit/uninstall'>;
}
