// flow-typed signature: c85dfcba752a79e5fea0b4028275d1f5
// flow-typed version: <<STUB>>/puppeteer_v^1.10.0/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'puppeteer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'puppeteer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'puppeteer/DeviceDescriptors' {
  declare module.exports: any;
}

declare module 'puppeteer/Errors' {
  declare module.exports: any;
}

declare module 'puppeteer/install' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Accessibility' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/api' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Browser' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/BrowserFetcher' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Connection' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Coverage' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/DeviceDescriptors' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Dialog' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/DOMWorld' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/EmulationManager' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Errors' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Events' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/ExecutionContext' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/FrameManager' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/helper' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Input' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/JSHandle' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Launcher' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/LifecycleWatcher' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Multimap' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/NetworkManager' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Page' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/PipeTransport' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Puppeteer' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Target' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/TaskQueue' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/TimeoutSettings' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Tracing' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/USKeyboardLayout' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/WebSocketTransport' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Worker' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/lib/Accessibility' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/lib/api' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/lib/Browser' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/lib/BrowserFetcher' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/lib/Connection' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/lib/Coverage' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/lib/DeviceDescriptors' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/lib/Dialog' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/lib/DOMWorld' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/lib/EmulationManager' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/lib/Errors' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/lib/Events' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/lib/ExecutionContext' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/lib/FrameManager' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/lib/helper' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/lib/Input' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/lib/JSHandle' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/lib/Launcher' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/lib/LifecycleWatcher' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/lib/Multimap' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/lib/NetworkManager' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/lib/Page' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/lib/PipeTransport' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/lib/Puppeteer' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/lib/Target' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/lib/TaskQueue' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/lib/TimeoutSettings' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/lib/Tracing' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/lib/USKeyboardLayout' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/lib/WebSocketTransport' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/lib/Worker' {
  declare module.exports: any;
}

declare module 'puppeteer/x' {
  declare module.exports: any;
}

// Filename aliases
declare module 'puppeteer/DeviceDescriptors.js' {
  declare module.exports: $Exports<'puppeteer/DeviceDescriptors'>;
}
declare module 'puppeteer/Errors.js' {
  declare module.exports: $Exports<'puppeteer/Errors'>;
}
declare module 'puppeteer/index' {
  declare module.exports: $Exports<'puppeteer'>;
}
declare module 'puppeteer/index.js' {
  declare module.exports: $Exports<'puppeteer'>;
}
declare module 'puppeteer/install.js' {
  declare module.exports: $Exports<'puppeteer/install'>;
}
declare module 'puppeteer/lib/Accessibility.js' {
  declare module.exports: $Exports<'puppeteer/lib/Accessibility'>;
}
declare module 'puppeteer/lib/api.js' {
  declare module.exports: $Exports<'puppeteer/lib/api'>;
}
declare module 'puppeteer/lib/Browser.js' {
  declare module.exports: $Exports<'puppeteer/lib/Browser'>;
}
declare module 'puppeteer/lib/BrowserFetcher.js' {
  declare module.exports: $Exports<'puppeteer/lib/BrowserFetcher'>;
}
declare module 'puppeteer/lib/Connection.js' {
  declare module.exports: $Exports<'puppeteer/lib/Connection'>;
}
declare module 'puppeteer/lib/Coverage.js' {
  declare module.exports: $Exports<'puppeteer/lib/Coverage'>;
}
declare module 'puppeteer/lib/DeviceDescriptors.js' {
  declare module.exports: $Exports<'puppeteer/lib/DeviceDescriptors'>;
}
declare module 'puppeteer/lib/Dialog.js' {
  declare module.exports: $Exports<'puppeteer/lib/Dialog'>;
}
declare module 'puppeteer/lib/DOMWorld.js' {
  declare module.exports: $Exports<'puppeteer/lib/DOMWorld'>;
}
declare module 'puppeteer/lib/EmulationManager.js' {
  declare module.exports: $Exports<'puppeteer/lib/EmulationManager'>;
}
declare module 'puppeteer/lib/Errors.js' {
  declare module.exports: $Exports<'puppeteer/lib/Errors'>;
}
declare module 'puppeteer/lib/Events.js' {
  declare module.exports: $Exports<'puppeteer/lib/Events'>;
}
declare module 'puppeteer/lib/ExecutionContext.js' {
  declare module.exports: $Exports<'puppeteer/lib/ExecutionContext'>;
}
declare module 'puppeteer/lib/FrameManager.js' {
  declare module.exports: $Exports<'puppeteer/lib/FrameManager'>;
}
declare module 'puppeteer/lib/helper.js' {
  declare module.exports: $Exports<'puppeteer/lib/helper'>;
}
declare module 'puppeteer/lib/Input.js' {
  declare module.exports: $Exports<'puppeteer/lib/Input'>;
}
declare module 'puppeteer/lib/JSHandle.js' {
  declare module.exports: $Exports<'puppeteer/lib/JSHandle'>;
}
declare module 'puppeteer/lib/Launcher.js' {
  declare module.exports: $Exports<'puppeteer/lib/Launcher'>;
}
declare module 'puppeteer/lib/LifecycleWatcher.js' {
  declare module.exports: $Exports<'puppeteer/lib/LifecycleWatcher'>;
}
declare module 'puppeteer/lib/Multimap.js' {
  declare module.exports: $Exports<'puppeteer/lib/Multimap'>;
}
declare module 'puppeteer/lib/NetworkManager.js' {
  declare module.exports: $Exports<'puppeteer/lib/NetworkManager'>;
}
declare module 'puppeteer/lib/Page.js' {
  declare module.exports: $Exports<'puppeteer/lib/Page'>;
}
declare module 'puppeteer/lib/PipeTransport.js' {
  declare module.exports: $Exports<'puppeteer/lib/PipeTransport'>;
}
declare module 'puppeteer/lib/Puppeteer.js' {
  declare module.exports: $Exports<'puppeteer/lib/Puppeteer'>;
}
declare module 'puppeteer/lib/Target.js' {
  declare module.exports: $Exports<'puppeteer/lib/Target'>;
}
declare module 'puppeteer/lib/TaskQueue.js' {
  declare module.exports: $Exports<'puppeteer/lib/TaskQueue'>;
}
declare module 'puppeteer/lib/TimeoutSettings.js' {
  declare module.exports: $Exports<'puppeteer/lib/TimeoutSettings'>;
}
declare module 'puppeteer/lib/Tracing.js' {
  declare module.exports: $Exports<'puppeteer/lib/Tracing'>;
}
declare module 'puppeteer/lib/USKeyboardLayout.js' {
  declare module.exports: $Exports<'puppeteer/lib/USKeyboardLayout'>;
}
declare module 'puppeteer/lib/WebSocketTransport.js' {
  declare module.exports: $Exports<'puppeteer/lib/WebSocketTransport'>;
}
declare module 'puppeteer/lib/Worker.js' {
  declare module.exports: $Exports<'puppeteer/lib/Worker'>;
}
declare module 'puppeteer/node6/lib/Accessibility.js' {
  declare module.exports: $Exports<'puppeteer/node6/lib/Accessibility'>;
}
declare module 'puppeteer/node6/lib/api.js' {
  declare module.exports: $Exports<'puppeteer/node6/lib/api'>;
}
declare module 'puppeteer/node6/lib/Browser.js' {
  declare module.exports: $Exports<'puppeteer/node6/lib/Browser'>;
}
declare module 'puppeteer/node6/lib/BrowserFetcher.js' {
  declare module.exports: $Exports<'puppeteer/node6/lib/BrowserFetcher'>;
}
declare module 'puppeteer/node6/lib/Connection.js' {
  declare module.exports: $Exports<'puppeteer/node6/lib/Connection'>;
}
declare module 'puppeteer/node6/lib/Coverage.js' {
  declare module.exports: $Exports<'puppeteer/node6/lib/Coverage'>;
}
declare module 'puppeteer/node6/lib/DeviceDescriptors.js' {
  declare module.exports: $Exports<'puppeteer/node6/lib/DeviceDescriptors'>;
}
declare module 'puppeteer/node6/lib/Dialog.js' {
  declare module.exports: $Exports<'puppeteer/node6/lib/Dialog'>;
}
declare module 'puppeteer/node6/lib/DOMWorld.js' {
  declare module.exports: $Exports<'puppeteer/node6/lib/DOMWorld'>;
}
declare module 'puppeteer/node6/lib/EmulationManager.js' {
  declare module.exports: $Exports<'puppeteer/node6/lib/EmulationManager'>;
}
declare module 'puppeteer/node6/lib/Errors.js' {
  declare module.exports: $Exports<'puppeteer/node6/lib/Errors'>;
}
declare module 'puppeteer/node6/lib/Events.js' {
  declare module.exports: $Exports<'puppeteer/node6/lib/Events'>;
}
declare module 'puppeteer/node6/lib/ExecutionContext.js' {
  declare module.exports: $Exports<'puppeteer/node6/lib/ExecutionContext'>;
}
declare module 'puppeteer/node6/lib/FrameManager.js' {
  declare module.exports: $Exports<'puppeteer/node6/lib/FrameManager'>;
}
declare module 'puppeteer/node6/lib/helper.js' {
  declare module.exports: $Exports<'puppeteer/node6/lib/helper'>;
}
declare module 'puppeteer/node6/lib/Input.js' {
  declare module.exports: $Exports<'puppeteer/node6/lib/Input'>;
}
declare module 'puppeteer/node6/lib/JSHandle.js' {
  declare module.exports: $Exports<'puppeteer/node6/lib/JSHandle'>;
}
declare module 'puppeteer/node6/lib/Launcher.js' {
  declare module.exports: $Exports<'puppeteer/node6/lib/Launcher'>;
}
declare module 'puppeteer/node6/lib/LifecycleWatcher.js' {
  declare module.exports: $Exports<'puppeteer/node6/lib/LifecycleWatcher'>;
}
declare module 'puppeteer/node6/lib/Multimap.js' {
  declare module.exports: $Exports<'puppeteer/node6/lib/Multimap'>;
}
declare module 'puppeteer/node6/lib/NetworkManager.js' {
  declare module.exports: $Exports<'puppeteer/node6/lib/NetworkManager'>;
}
declare module 'puppeteer/node6/lib/Page.js' {
  declare module.exports: $Exports<'puppeteer/node6/lib/Page'>;
}
declare module 'puppeteer/node6/lib/PipeTransport.js' {
  declare module.exports: $Exports<'puppeteer/node6/lib/PipeTransport'>;
}
declare module 'puppeteer/node6/lib/Puppeteer.js' {
  declare module.exports: $Exports<'puppeteer/node6/lib/Puppeteer'>;
}
declare module 'puppeteer/node6/lib/Target.js' {
  declare module.exports: $Exports<'puppeteer/node6/lib/Target'>;
}
declare module 'puppeteer/node6/lib/TaskQueue.js' {
  declare module.exports: $Exports<'puppeteer/node6/lib/TaskQueue'>;
}
declare module 'puppeteer/node6/lib/TimeoutSettings.js' {
  declare module.exports: $Exports<'puppeteer/node6/lib/TimeoutSettings'>;
}
declare module 'puppeteer/node6/lib/Tracing.js' {
  declare module.exports: $Exports<'puppeteer/node6/lib/Tracing'>;
}
declare module 'puppeteer/node6/lib/USKeyboardLayout.js' {
  declare module.exports: $Exports<'puppeteer/node6/lib/USKeyboardLayout'>;
}
declare module 'puppeteer/node6/lib/WebSocketTransport.js' {
  declare module.exports: $Exports<'puppeteer/node6/lib/WebSocketTransport'>;
}
declare module 'puppeteer/node6/lib/Worker.js' {
  declare module.exports: $Exports<'puppeteer/node6/lib/Worker'>;
}
declare module 'puppeteer/x.js' {
  declare module.exports: $Exports<'puppeteer/x'>;
}
