// flow-typed signature: a11525658fa561d9f8adc04423e9c7a5
// flow-typed version: <<STUB>>/raf_v^3.4.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'raf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'raf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'raf/polyfill' {
  declare module.exports: any;
}

declare module 'raf/test' {
  declare module.exports: any;
}

declare module 'raf/window' {
  declare module.exports: any;
}

// Filename aliases
declare module 'raf/index' {
  declare module.exports: $Exports<'raf'>;
}
declare module 'raf/index.js' {
  declare module.exports: $Exports<'raf'>;
}
declare module 'raf/polyfill.js' {
  declare module.exports: $Exports<'raf/polyfill'>;
}
declare module 'raf/test.js' {
  declare module.exports: $Exports<'raf/test'>;
}
declare module 'raf/window.js' {
  declare module.exports: $Exports<'raf/window'>;
}
