// flow-typed signature: 2f036fce35c841a66a3acc231ebe64c5
// flow-typed version: <<STUB>>/react-primitives_v^0.8.0/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-primitives'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-primitives' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-primitives/lib/index.android' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/index.ios' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/index' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/index.sketch' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/index.vr' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/index.web' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/index.windows' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/injection/react-native-web' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/injection/react-native' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/injection/react-sketchapp' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/injection/react-vr' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/modules/PixelRatio' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/modules/Platform' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/modules/Touchable' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/ReactPrimitives' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/vr/Touchable' {
  declare module.exports: any;
}

declare module 'react-primitives/scripts/getSHARangeFromPR' {
  declare module.exports: any;
}

declare module 'react-primitives/scripts/updatePR' {
  declare module.exports: any;
}

declare module 'react-primitives/src/index.android' {
  declare module.exports: any;
}

declare module 'react-primitives/src/index.ios' {
  declare module.exports: any;
}

declare module 'react-primitives/src/index' {
  declare module.exports: any;
}

declare module 'react-primitives/src/index.sketch' {
  declare module.exports: any;
}

declare module 'react-primitives/src/index.vr' {
  declare module.exports: any;
}

declare module 'react-primitives/src/index.web' {
  declare module.exports: any;
}

declare module 'react-primitives/src/index.windows' {
  declare module.exports: any;
}

declare module 'react-primitives/src/injection/react-native-web' {
  declare module.exports: any;
}

declare module 'react-primitives/src/injection/react-native' {
  declare module.exports: any;
}

declare module 'react-primitives/src/injection/react-sketchapp' {
  declare module.exports: any;
}

declare module 'react-primitives/src/injection/react-vr' {
  declare module.exports: any;
}

declare module 'react-primitives/src/modules/PixelRatio' {
  declare module.exports: any;
}

declare module 'react-primitives/src/modules/Platform' {
  declare module.exports: any;
}

declare module 'react-primitives/src/modules/Touchable' {
  declare module.exports: any;
}

declare module 'react-primitives/src/ReactPrimitives' {
  declare module.exports: any;
}

declare module 'react-primitives/src/vr/Touchable' {
  declare module.exports: any;
}

declare module 'react-primitives/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-primitives/index' {
  declare module.exports: $Exports<'react-primitives'>;
}
declare module 'react-primitives/index.js' {
  declare module.exports: $Exports<'react-primitives'>;
}
declare module 'react-primitives/lib/index.android.js' {
  declare module.exports: $Exports<'react-primitives/lib/index.android'>;
}
declare module 'react-primitives/lib/index.ios.js' {
  declare module.exports: $Exports<'react-primitives/lib/index.ios'>;
}
declare module 'react-primitives/lib/index.js' {
  declare module.exports: $Exports<'react-primitives/lib/index'>;
}
declare module 'react-primitives/lib/index.sketch.js' {
  declare module.exports: $Exports<'react-primitives/lib/index.sketch'>;
}
declare module 'react-primitives/lib/index.vr.js' {
  declare module.exports: $Exports<'react-primitives/lib/index.vr'>;
}
declare module 'react-primitives/lib/index.web.js' {
  declare module.exports: $Exports<'react-primitives/lib/index.web'>;
}
declare module 'react-primitives/lib/index.windows.js' {
  declare module.exports: $Exports<'react-primitives/lib/index.windows'>;
}
declare module 'react-primitives/lib/injection/react-native-web.js' {
  declare module.exports: $Exports<'react-primitives/lib/injection/react-native-web'>;
}
declare module 'react-primitives/lib/injection/react-native.js' {
  declare module.exports: $Exports<'react-primitives/lib/injection/react-native'>;
}
declare module 'react-primitives/lib/injection/react-sketchapp.js' {
  declare module.exports: $Exports<'react-primitives/lib/injection/react-sketchapp'>;
}
declare module 'react-primitives/lib/injection/react-vr.js' {
  declare module.exports: $Exports<'react-primitives/lib/injection/react-vr'>;
}
declare module 'react-primitives/lib/modules/PixelRatio.js' {
  declare module.exports: $Exports<'react-primitives/lib/modules/PixelRatio'>;
}
declare module 'react-primitives/lib/modules/Platform.js' {
  declare module.exports: $Exports<'react-primitives/lib/modules/Platform'>;
}
declare module 'react-primitives/lib/modules/Touchable.js' {
  declare module.exports: $Exports<'react-primitives/lib/modules/Touchable'>;
}
declare module 'react-primitives/lib/ReactPrimitives.js' {
  declare module.exports: $Exports<'react-primitives/lib/ReactPrimitives'>;
}
declare module 'react-primitives/lib/vr/Touchable.js' {
  declare module.exports: $Exports<'react-primitives/lib/vr/Touchable'>;
}
declare module 'react-primitives/scripts/getSHARangeFromPR.js' {
  declare module.exports: $Exports<'react-primitives/scripts/getSHARangeFromPR'>;
}
declare module 'react-primitives/scripts/updatePR.js' {
  declare module.exports: $Exports<'react-primitives/scripts/updatePR'>;
}
declare module 'react-primitives/src/index.android.js' {
  declare module.exports: $Exports<'react-primitives/src/index.android'>;
}
declare module 'react-primitives/src/index.ios.js' {
  declare module.exports: $Exports<'react-primitives/src/index.ios'>;
}
declare module 'react-primitives/src/index.js' {
  declare module.exports: $Exports<'react-primitives/src/index'>;
}
declare module 'react-primitives/src/index.sketch.js' {
  declare module.exports: $Exports<'react-primitives/src/index.sketch'>;
}
declare module 'react-primitives/src/index.vr.js' {
  declare module.exports: $Exports<'react-primitives/src/index.vr'>;
}
declare module 'react-primitives/src/index.web.js' {
  declare module.exports: $Exports<'react-primitives/src/index.web'>;
}
declare module 'react-primitives/src/index.windows.js' {
  declare module.exports: $Exports<'react-primitives/src/index.windows'>;
}
declare module 'react-primitives/src/injection/react-native-web.js' {
  declare module.exports: $Exports<'react-primitives/src/injection/react-native-web'>;
}
declare module 'react-primitives/src/injection/react-native.js' {
  declare module.exports: $Exports<'react-primitives/src/injection/react-native'>;
}
declare module 'react-primitives/src/injection/react-sketchapp.js' {
  declare module.exports: $Exports<'react-primitives/src/injection/react-sketchapp'>;
}
declare module 'react-primitives/src/injection/react-vr.js' {
  declare module.exports: $Exports<'react-primitives/src/injection/react-vr'>;
}
declare module 'react-primitives/src/modules/PixelRatio.js' {
  declare module.exports: $Exports<'react-primitives/src/modules/PixelRatio'>;
}
declare module 'react-primitives/src/modules/Platform.js' {
  declare module.exports: $Exports<'react-primitives/src/modules/Platform'>;
}
declare module 'react-primitives/src/modules/Touchable.js' {
  declare module.exports: $Exports<'react-primitives/src/modules/Touchable'>;
}
declare module 'react-primitives/src/ReactPrimitives.js' {
  declare module.exports: $Exports<'react-primitives/src/ReactPrimitives'>;
}
declare module 'react-primitives/src/vr/Touchable.js' {
  declare module.exports: $Exports<'react-primitives/src/vr/Touchable'>;
}
declare module 'react-primitives/webpack.config.js' {
  declare module.exports: $Exports<'react-primitives/webpack.config'>;
}
