// flow-typed signature: 8a0ade948aba15727fdaff66ba6efcff
// flow-typed version: <<STUB>>/react-primitives_v^0.5.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-primitives'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-primitives' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-primitives/lib/index.android' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/index.ios' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/index' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/index.sketch' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/index.vr' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/index.web' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/injection/react-native-web' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/injection/react-native' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/injection/react-sketchapp' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/injection/react-vr' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/injection/react-web' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/modules/PixelRatio' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/modules/Platform' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/modules/Touchable' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/ReactPrimitives' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/vr/Touchable' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/Image/Image' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/Image/ImageResizeMode' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/Image/ImageStylePropTypes' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/Image/resolveAssetSource' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/propTypes/Accessibility' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/propTypes/BorderPropTypes' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/propTypes/ColorPropType' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/propTypes/createStrictShapeTypeChecker' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/propTypes/LayoutPropTypes' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/propTypes/ShadowPropTypes' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/propTypes/StyleSheetPropType' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/propTypes/TransformPropTypes' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/StyleSheet/__tests__/initialStyles-tests' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/StyleSheet/__tests__/normalizeValue-tests' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/StyleSheet/__tests__/StyleSheet-tests' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/StyleSheet/__tests__/transformToWebStyle-tests' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/StyleSheet/generateCss' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/StyleSheet/getHairlineWidth' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/StyleSheet/hyphenate' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/StyleSheet/index' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/StyleSheet/initialStyles' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/StyleSheet/injector' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/StyleSheet/normalizeValue' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/StyleSheet/prefixedProperties' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/StyleSheet/registry' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/StyleSheet/test-utils' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/StyleSheet/transformToWebStyle' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/Text/__tests__/Text-tests' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/Text/Text' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/Text/TextStylePropTypes' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/Touchable/BoundingDimensions' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/Touchable/ensureComponentisNative' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/Touchable/ensurePositiveDelayProps' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/Touchable/injectResponderEventPlugin' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/Touchable/normalizeNativeEvent' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/Touchable/PooledClass' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/Touchable/Position' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/Touchable/Touchable' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/Touchable/TouchableMixin' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/Touchable/TouchEventUtils' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/UIManager' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/util/applyOnLayoutHandling' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/util/applyPrimitiveMethods' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/util/colorWithOpacity' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/util/flexboxSupport' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/util/keyMirror' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/util/mapKeyValue' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/util/throttleAndDebounce' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/View/__tests__/View-tests' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/View/View' {
  declare module.exports: any;
}

declare module 'react-primitives/lib/web/View/ViewStylePropTypes' {
  declare module.exports: any;
}

declare module 'react-primitives/scripts/getSHARangeFromPR' {
  declare module.exports: any;
}

declare module 'react-primitives/scripts/updatePR' {
  declare module.exports: any;
}

declare module 'react-primitives/src/index.android' {
  declare module.exports: any;
}

declare module 'react-primitives/src/index.ios' {
  declare module.exports: any;
}

declare module 'react-primitives/src/index' {
  declare module.exports: any;
}

declare module 'react-primitives/src/index.sketch' {
  declare module.exports: any;
}

declare module 'react-primitives/src/index.vr' {
  declare module.exports: any;
}

declare module 'react-primitives/src/index.web' {
  declare module.exports: any;
}

declare module 'react-primitives/src/injection/react-native-web' {
  declare module.exports: any;
}

declare module 'react-primitives/src/injection/react-native' {
  declare module.exports: any;
}

declare module 'react-primitives/src/injection/react-sketchapp' {
  declare module.exports: any;
}

declare module 'react-primitives/src/injection/react-vr' {
  declare module.exports: any;
}

declare module 'react-primitives/src/injection/react-web' {
  declare module.exports: any;
}

declare module 'react-primitives/src/modules/PixelRatio' {
  declare module.exports: any;
}

declare module 'react-primitives/src/modules/Platform' {
  declare module.exports: any;
}

declare module 'react-primitives/src/modules/Touchable' {
  declare module.exports: any;
}

declare module 'react-primitives/src/ReactPrimitives' {
  declare module.exports: any;
}

declare module 'react-primitives/src/vr/Touchable' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/Image/Image' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/Image/ImageResizeMode' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/Image/ImageStylePropTypes' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/Image/resolveAssetSource' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/propTypes/Accessibility' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/propTypes/BorderPropTypes' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/propTypes/ColorPropType' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/propTypes/createStrictShapeTypeChecker' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/propTypes/LayoutPropTypes' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/propTypes/ShadowPropTypes' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/propTypes/StyleSheetPropType' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/propTypes/TransformPropTypes' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/StyleSheet/__tests__/initialStyles-tests' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/StyleSheet/__tests__/normalizeValue-tests' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/StyleSheet/__tests__/StyleSheet-tests' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/StyleSheet/__tests__/transformToWebStyle-tests' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/StyleSheet/generateCss' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/StyleSheet/getHairlineWidth' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/StyleSheet/hyphenate' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/StyleSheet/index' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/StyleSheet/initialStyles' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/StyleSheet/injector' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/StyleSheet/normalizeValue' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/StyleSheet/prefixedProperties' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/StyleSheet/registry' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/StyleSheet/test-utils' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/StyleSheet/transformToWebStyle' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/Text/__tests__/Text-tests' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/Text/Text' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/Text/TextStylePropTypes' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/Touchable/BoundingDimensions' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/Touchable/ensureComponentisNative' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/Touchable/ensurePositiveDelayProps' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/Touchable/injectResponderEventPlugin' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/Touchable/normalizeNativeEvent' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/Touchable/PooledClass' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/Touchable/Position' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/Touchable/Touchable' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/Touchable/TouchableMixin' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/Touchable/TouchEventUtils' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/UIManager' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/util/applyOnLayoutHandling' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/util/applyPrimitiveMethods' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/util/colorWithOpacity' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/util/flexboxSupport' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/util/keyMirror' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/util/mapKeyValue' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/util/throttleAndDebounce' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/View/__tests__/View-tests' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/View/View' {
  declare module.exports: any;
}

declare module 'react-primitives/src/web/View/ViewStylePropTypes' {
  declare module.exports: any;
}

declare module 'react-primitives/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-primitives/index' {
  declare module.exports: $Exports<'react-primitives'>;
}
declare module 'react-primitives/index.js' {
  declare module.exports: $Exports<'react-primitives'>;
}
declare module 'react-primitives/lib/index.android.js' {
  declare module.exports: $Exports<'react-primitives/lib/index.android'>;
}
declare module 'react-primitives/lib/index.ios.js' {
  declare module.exports: $Exports<'react-primitives/lib/index.ios'>;
}
declare module 'react-primitives/lib/index.js' {
  declare module.exports: $Exports<'react-primitives/lib/index'>;
}
declare module 'react-primitives/lib/index.sketch.js' {
  declare module.exports: $Exports<'react-primitives/lib/index.sketch'>;
}
declare module 'react-primitives/lib/index.vr.js' {
  declare module.exports: $Exports<'react-primitives/lib/index.vr'>;
}
declare module 'react-primitives/lib/index.web.js' {
  declare module.exports: $Exports<'react-primitives/lib/index.web'>;
}
declare module 'react-primitives/lib/injection/react-native-web.js' {
  declare module.exports: $Exports<'react-primitives/lib/injection/react-native-web'>;
}
declare module 'react-primitives/lib/injection/react-native.js' {
  declare module.exports: $Exports<'react-primitives/lib/injection/react-native'>;
}
declare module 'react-primitives/lib/injection/react-sketchapp.js' {
  declare module.exports: $Exports<'react-primitives/lib/injection/react-sketchapp'>;
}
declare module 'react-primitives/lib/injection/react-vr.js' {
  declare module.exports: $Exports<'react-primitives/lib/injection/react-vr'>;
}
declare module 'react-primitives/lib/injection/react-web.js' {
  declare module.exports: $Exports<'react-primitives/lib/injection/react-web'>;
}
declare module 'react-primitives/lib/modules/PixelRatio.js' {
  declare module.exports: $Exports<'react-primitives/lib/modules/PixelRatio'>;
}
declare module 'react-primitives/lib/modules/Platform.js' {
  declare module.exports: $Exports<'react-primitives/lib/modules/Platform'>;
}
declare module 'react-primitives/lib/modules/Touchable.js' {
  declare module.exports: $Exports<'react-primitives/lib/modules/Touchable'>;
}
declare module 'react-primitives/lib/ReactPrimitives.js' {
  declare module.exports: $Exports<'react-primitives/lib/ReactPrimitives'>;
}
declare module 'react-primitives/lib/vr/Touchable.js' {
  declare module.exports: $Exports<'react-primitives/lib/vr/Touchable'>;
}
declare module 'react-primitives/lib/web/Image/Image.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/Image/Image'>;
}
declare module 'react-primitives/lib/web/Image/ImageResizeMode.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/Image/ImageResizeMode'>;
}
declare module 'react-primitives/lib/web/Image/ImageStylePropTypes.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/Image/ImageStylePropTypes'>;
}
declare module 'react-primitives/lib/web/Image/resolveAssetSource.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/Image/resolveAssetSource'>;
}
declare module 'react-primitives/lib/web/propTypes/Accessibility.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/propTypes/Accessibility'>;
}
declare module 'react-primitives/lib/web/propTypes/BorderPropTypes.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/propTypes/BorderPropTypes'>;
}
declare module 'react-primitives/lib/web/propTypes/ColorPropType.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/propTypes/ColorPropType'>;
}
declare module 'react-primitives/lib/web/propTypes/createStrictShapeTypeChecker.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/propTypes/createStrictShapeTypeChecker'>;
}
declare module 'react-primitives/lib/web/propTypes/LayoutPropTypes.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/propTypes/LayoutPropTypes'>;
}
declare module 'react-primitives/lib/web/propTypes/ShadowPropTypes.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/propTypes/ShadowPropTypes'>;
}
declare module 'react-primitives/lib/web/propTypes/StyleSheetPropType.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/propTypes/StyleSheetPropType'>;
}
declare module 'react-primitives/lib/web/propTypes/TransformPropTypes.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/propTypes/TransformPropTypes'>;
}
declare module 'react-primitives/lib/web/StyleSheet/__tests__/initialStyles-tests.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/StyleSheet/__tests__/initialStyles-tests'>;
}
declare module 'react-primitives/lib/web/StyleSheet/__tests__/normalizeValue-tests.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/StyleSheet/__tests__/normalizeValue-tests'>;
}
declare module 'react-primitives/lib/web/StyleSheet/__tests__/StyleSheet-tests.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/StyleSheet/__tests__/StyleSheet-tests'>;
}
declare module 'react-primitives/lib/web/StyleSheet/__tests__/transformToWebStyle-tests.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/StyleSheet/__tests__/transformToWebStyle-tests'>;
}
declare module 'react-primitives/lib/web/StyleSheet/generateCss.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/StyleSheet/generateCss'>;
}
declare module 'react-primitives/lib/web/StyleSheet/getHairlineWidth.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/StyleSheet/getHairlineWidth'>;
}
declare module 'react-primitives/lib/web/StyleSheet/hyphenate.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/StyleSheet/hyphenate'>;
}
declare module 'react-primitives/lib/web/StyleSheet/index.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/StyleSheet/index'>;
}
declare module 'react-primitives/lib/web/StyleSheet/initialStyles.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/StyleSheet/initialStyles'>;
}
declare module 'react-primitives/lib/web/StyleSheet/injector.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/StyleSheet/injector'>;
}
declare module 'react-primitives/lib/web/StyleSheet/normalizeValue.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/StyleSheet/normalizeValue'>;
}
declare module 'react-primitives/lib/web/StyleSheet/prefixedProperties.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/StyleSheet/prefixedProperties'>;
}
declare module 'react-primitives/lib/web/StyleSheet/registry.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/StyleSheet/registry'>;
}
declare module 'react-primitives/lib/web/StyleSheet/test-utils.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/StyleSheet/test-utils'>;
}
declare module 'react-primitives/lib/web/StyleSheet/transformToWebStyle.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/StyleSheet/transformToWebStyle'>;
}
declare module 'react-primitives/lib/web/Text/__tests__/Text-tests.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/Text/__tests__/Text-tests'>;
}
declare module 'react-primitives/lib/web/Text/Text.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/Text/Text'>;
}
declare module 'react-primitives/lib/web/Text/TextStylePropTypes.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/Text/TextStylePropTypes'>;
}
declare module 'react-primitives/lib/web/Touchable/BoundingDimensions.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/Touchable/BoundingDimensions'>;
}
declare module 'react-primitives/lib/web/Touchable/ensureComponentisNative.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/Touchable/ensureComponentisNative'>;
}
declare module 'react-primitives/lib/web/Touchable/ensurePositiveDelayProps.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/Touchable/ensurePositiveDelayProps'>;
}
declare module 'react-primitives/lib/web/Touchable/injectResponderEventPlugin.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/Touchable/injectResponderEventPlugin'>;
}
declare module 'react-primitives/lib/web/Touchable/normalizeNativeEvent.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/Touchable/normalizeNativeEvent'>;
}
declare module 'react-primitives/lib/web/Touchable/PooledClass.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/Touchable/PooledClass'>;
}
declare module 'react-primitives/lib/web/Touchable/Position.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/Touchable/Position'>;
}
declare module 'react-primitives/lib/web/Touchable/Touchable.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/Touchable/Touchable'>;
}
declare module 'react-primitives/lib/web/Touchable/TouchableMixin.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/Touchable/TouchableMixin'>;
}
declare module 'react-primitives/lib/web/Touchable/TouchEventUtils.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/Touchable/TouchEventUtils'>;
}
declare module 'react-primitives/lib/web/UIManager.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/UIManager'>;
}
declare module 'react-primitives/lib/web/util/applyOnLayoutHandling.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/util/applyOnLayoutHandling'>;
}
declare module 'react-primitives/lib/web/util/applyPrimitiveMethods.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/util/applyPrimitiveMethods'>;
}
declare module 'react-primitives/lib/web/util/colorWithOpacity.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/util/colorWithOpacity'>;
}
declare module 'react-primitives/lib/web/util/flexboxSupport.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/util/flexboxSupport'>;
}
declare module 'react-primitives/lib/web/util/keyMirror.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/util/keyMirror'>;
}
declare module 'react-primitives/lib/web/util/mapKeyValue.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/util/mapKeyValue'>;
}
declare module 'react-primitives/lib/web/util/throttleAndDebounce.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/util/throttleAndDebounce'>;
}
declare module 'react-primitives/lib/web/View/__tests__/View-tests.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/View/__tests__/View-tests'>;
}
declare module 'react-primitives/lib/web/View/View.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/View/View'>;
}
declare module 'react-primitives/lib/web/View/ViewStylePropTypes.js' {
  declare module.exports: $Exports<'react-primitives/lib/web/View/ViewStylePropTypes'>;
}
declare module 'react-primitives/scripts/getSHARangeFromPR.js' {
  declare module.exports: $Exports<'react-primitives/scripts/getSHARangeFromPR'>;
}
declare module 'react-primitives/scripts/updatePR.js' {
  declare module.exports: $Exports<'react-primitives/scripts/updatePR'>;
}
declare module 'react-primitives/src/index.android.js' {
  declare module.exports: $Exports<'react-primitives/src/index.android'>;
}
declare module 'react-primitives/src/index.ios.js' {
  declare module.exports: $Exports<'react-primitives/src/index.ios'>;
}
declare module 'react-primitives/src/index.js' {
  declare module.exports: $Exports<'react-primitives/src/index'>;
}
declare module 'react-primitives/src/index.sketch.js' {
  declare module.exports: $Exports<'react-primitives/src/index.sketch'>;
}
declare module 'react-primitives/src/index.vr.js' {
  declare module.exports: $Exports<'react-primitives/src/index.vr'>;
}
declare module 'react-primitives/src/index.web.js' {
  declare module.exports: $Exports<'react-primitives/src/index.web'>;
}
declare module 'react-primitives/src/injection/react-native-web.js' {
  declare module.exports: $Exports<'react-primitives/src/injection/react-native-web'>;
}
declare module 'react-primitives/src/injection/react-native.js' {
  declare module.exports: $Exports<'react-primitives/src/injection/react-native'>;
}
declare module 'react-primitives/src/injection/react-sketchapp.js' {
  declare module.exports: $Exports<'react-primitives/src/injection/react-sketchapp'>;
}
declare module 'react-primitives/src/injection/react-vr.js' {
  declare module.exports: $Exports<'react-primitives/src/injection/react-vr'>;
}
declare module 'react-primitives/src/injection/react-web.js' {
  declare module.exports: $Exports<'react-primitives/src/injection/react-web'>;
}
declare module 'react-primitives/src/modules/PixelRatio.js' {
  declare module.exports: $Exports<'react-primitives/src/modules/PixelRatio'>;
}
declare module 'react-primitives/src/modules/Platform.js' {
  declare module.exports: $Exports<'react-primitives/src/modules/Platform'>;
}
declare module 'react-primitives/src/modules/Touchable.js' {
  declare module.exports: $Exports<'react-primitives/src/modules/Touchable'>;
}
declare module 'react-primitives/src/ReactPrimitives.js' {
  declare module.exports: $Exports<'react-primitives/src/ReactPrimitives'>;
}
declare module 'react-primitives/src/vr/Touchable.js' {
  declare module.exports: $Exports<'react-primitives/src/vr/Touchable'>;
}
declare module 'react-primitives/src/web/Image/Image.js' {
  declare module.exports: $Exports<'react-primitives/src/web/Image/Image'>;
}
declare module 'react-primitives/src/web/Image/ImageResizeMode.js' {
  declare module.exports: $Exports<'react-primitives/src/web/Image/ImageResizeMode'>;
}
declare module 'react-primitives/src/web/Image/ImageStylePropTypes.js' {
  declare module.exports: $Exports<'react-primitives/src/web/Image/ImageStylePropTypes'>;
}
declare module 'react-primitives/src/web/Image/resolveAssetSource.js' {
  declare module.exports: $Exports<'react-primitives/src/web/Image/resolveAssetSource'>;
}
declare module 'react-primitives/src/web/propTypes/Accessibility.js' {
  declare module.exports: $Exports<'react-primitives/src/web/propTypes/Accessibility'>;
}
declare module 'react-primitives/src/web/propTypes/BorderPropTypes.js' {
  declare module.exports: $Exports<'react-primitives/src/web/propTypes/BorderPropTypes'>;
}
declare module 'react-primitives/src/web/propTypes/ColorPropType.js' {
  declare module.exports: $Exports<'react-primitives/src/web/propTypes/ColorPropType'>;
}
declare module 'react-primitives/src/web/propTypes/createStrictShapeTypeChecker.js' {
  declare module.exports: $Exports<'react-primitives/src/web/propTypes/createStrictShapeTypeChecker'>;
}
declare module 'react-primitives/src/web/propTypes/LayoutPropTypes.js' {
  declare module.exports: $Exports<'react-primitives/src/web/propTypes/LayoutPropTypes'>;
}
declare module 'react-primitives/src/web/propTypes/ShadowPropTypes.js' {
  declare module.exports: $Exports<'react-primitives/src/web/propTypes/ShadowPropTypes'>;
}
declare module 'react-primitives/src/web/propTypes/StyleSheetPropType.js' {
  declare module.exports: $Exports<'react-primitives/src/web/propTypes/StyleSheetPropType'>;
}
declare module 'react-primitives/src/web/propTypes/TransformPropTypes.js' {
  declare module.exports: $Exports<'react-primitives/src/web/propTypes/TransformPropTypes'>;
}
declare module 'react-primitives/src/web/StyleSheet/__tests__/initialStyles-tests.js' {
  declare module.exports: $Exports<'react-primitives/src/web/StyleSheet/__tests__/initialStyles-tests'>;
}
declare module 'react-primitives/src/web/StyleSheet/__tests__/normalizeValue-tests.js' {
  declare module.exports: $Exports<'react-primitives/src/web/StyleSheet/__tests__/normalizeValue-tests'>;
}
declare module 'react-primitives/src/web/StyleSheet/__tests__/StyleSheet-tests.js' {
  declare module.exports: $Exports<'react-primitives/src/web/StyleSheet/__tests__/StyleSheet-tests'>;
}
declare module 'react-primitives/src/web/StyleSheet/__tests__/transformToWebStyle-tests.js' {
  declare module.exports: $Exports<'react-primitives/src/web/StyleSheet/__tests__/transformToWebStyle-tests'>;
}
declare module 'react-primitives/src/web/StyleSheet/generateCss.js' {
  declare module.exports: $Exports<'react-primitives/src/web/StyleSheet/generateCss'>;
}
declare module 'react-primitives/src/web/StyleSheet/getHairlineWidth.js' {
  declare module.exports: $Exports<'react-primitives/src/web/StyleSheet/getHairlineWidth'>;
}
declare module 'react-primitives/src/web/StyleSheet/hyphenate.js' {
  declare module.exports: $Exports<'react-primitives/src/web/StyleSheet/hyphenate'>;
}
declare module 'react-primitives/src/web/StyleSheet/index.js' {
  declare module.exports: $Exports<'react-primitives/src/web/StyleSheet/index'>;
}
declare module 'react-primitives/src/web/StyleSheet/initialStyles.js' {
  declare module.exports: $Exports<'react-primitives/src/web/StyleSheet/initialStyles'>;
}
declare module 'react-primitives/src/web/StyleSheet/injector.js' {
  declare module.exports: $Exports<'react-primitives/src/web/StyleSheet/injector'>;
}
declare module 'react-primitives/src/web/StyleSheet/normalizeValue.js' {
  declare module.exports: $Exports<'react-primitives/src/web/StyleSheet/normalizeValue'>;
}
declare module 'react-primitives/src/web/StyleSheet/prefixedProperties.js' {
  declare module.exports: $Exports<'react-primitives/src/web/StyleSheet/prefixedProperties'>;
}
declare module 'react-primitives/src/web/StyleSheet/registry.js' {
  declare module.exports: $Exports<'react-primitives/src/web/StyleSheet/registry'>;
}
declare module 'react-primitives/src/web/StyleSheet/test-utils.js' {
  declare module.exports: $Exports<'react-primitives/src/web/StyleSheet/test-utils'>;
}
declare module 'react-primitives/src/web/StyleSheet/transformToWebStyle.js' {
  declare module.exports: $Exports<'react-primitives/src/web/StyleSheet/transformToWebStyle'>;
}
declare module 'react-primitives/src/web/Text/__tests__/Text-tests.js' {
  declare module.exports: $Exports<'react-primitives/src/web/Text/__tests__/Text-tests'>;
}
declare module 'react-primitives/src/web/Text/Text.js' {
  declare module.exports: $Exports<'react-primitives/src/web/Text/Text'>;
}
declare module 'react-primitives/src/web/Text/TextStylePropTypes.js' {
  declare module.exports: $Exports<'react-primitives/src/web/Text/TextStylePropTypes'>;
}
declare module 'react-primitives/src/web/Touchable/BoundingDimensions.js' {
  declare module.exports: $Exports<'react-primitives/src/web/Touchable/BoundingDimensions'>;
}
declare module 'react-primitives/src/web/Touchable/ensureComponentisNative.js' {
  declare module.exports: $Exports<'react-primitives/src/web/Touchable/ensureComponentisNative'>;
}
declare module 'react-primitives/src/web/Touchable/ensurePositiveDelayProps.js' {
  declare module.exports: $Exports<'react-primitives/src/web/Touchable/ensurePositiveDelayProps'>;
}
declare module 'react-primitives/src/web/Touchable/injectResponderEventPlugin.js' {
  declare module.exports: $Exports<'react-primitives/src/web/Touchable/injectResponderEventPlugin'>;
}
declare module 'react-primitives/src/web/Touchable/normalizeNativeEvent.js' {
  declare module.exports: $Exports<'react-primitives/src/web/Touchable/normalizeNativeEvent'>;
}
declare module 'react-primitives/src/web/Touchable/PooledClass.js' {
  declare module.exports: $Exports<'react-primitives/src/web/Touchable/PooledClass'>;
}
declare module 'react-primitives/src/web/Touchable/Position.js' {
  declare module.exports: $Exports<'react-primitives/src/web/Touchable/Position'>;
}
declare module 'react-primitives/src/web/Touchable/Touchable.js' {
  declare module.exports: $Exports<'react-primitives/src/web/Touchable/Touchable'>;
}
declare module 'react-primitives/src/web/Touchable/TouchableMixin.js' {
  declare module.exports: $Exports<'react-primitives/src/web/Touchable/TouchableMixin'>;
}
declare module 'react-primitives/src/web/Touchable/TouchEventUtils.js' {
  declare module.exports: $Exports<'react-primitives/src/web/Touchable/TouchEventUtils'>;
}
declare module 'react-primitives/src/web/UIManager.js' {
  declare module.exports: $Exports<'react-primitives/src/web/UIManager'>;
}
declare module 'react-primitives/src/web/util/applyOnLayoutHandling.js' {
  declare module.exports: $Exports<'react-primitives/src/web/util/applyOnLayoutHandling'>;
}
declare module 'react-primitives/src/web/util/applyPrimitiveMethods.js' {
  declare module.exports: $Exports<'react-primitives/src/web/util/applyPrimitiveMethods'>;
}
declare module 'react-primitives/src/web/util/colorWithOpacity.js' {
  declare module.exports: $Exports<'react-primitives/src/web/util/colorWithOpacity'>;
}
declare module 'react-primitives/src/web/util/flexboxSupport.js' {
  declare module.exports: $Exports<'react-primitives/src/web/util/flexboxSupport'>;
}
declare module 'react-primitives/src/web/util/keyMirror.js' {
  declare module.exports: $Exports<'react-primitives/src/web/util/keyMirror'>;
}
declare module 'react-primitives/src/web/util/mapKeyValue.js' {
  declare module.exports: $Exports<'react-primitives/src/web/util/mapKeyValue'>;
}
declare module 'react-primitives/src/web/util/throttleAndDebounce.js' {
  declare module.exports: $Exports<'react-primitives/src/web/util/throttleAndDebounce'>;
}
declare module 'react-primitives/src/web/View/__tests__/View-tests.js' {
  declare module.exports: $Exports<'react-primitives/src/web/View/__tests__/View-tests'>;
}
declare module 'react-primitives/src/web/View/View.js' {
  declare module.exports: $Exports<'react-primitives/src/web/View/View'>;
}
declare module 'react-primitives/src/web/View/ViewStylePropTypes.js' {
  declare module.exports: $Exports<'react-primitives/src/web/View/ViewStylePropTypes'>;
}
declare module 'react-primitives/webpack.config.js' {
  declare module.exports: $Exports<'react-primitives/webpack.config'>;
}
