// flow-typed signature: bc169fc1f795f27e80e3bdcb2a5e87d1
// flow-typed version: <<STUB>>/react-testing-library_v^4.1.7/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-testing-library'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-testing-library' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-testing-library/cleanup-after-each' {
  declare module.exports: any;
}

declare module 'react-testing-library/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-testing-library/cleanup-after-each.js' {
  declare module.exports: $Exports<'react-testing-library/cleanup-after-each'>;
}
declare module 'react-testing-library/dist/index.js' {
  declare module.exports: $Exports<'react-testing-library/dist/index'>;
}
