// flow-typed signature: 3da1f41fe3c1eac4ec9566f7bebc64de
// flow-typed version: <<STUB>>/react-is_v>= 16.8.0/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-is'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-is' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-is/cjs/react-is.development' {
  declare module.exports: any;
}

declare module 'react-is/cjs/react-is.production.min' {
  declare module.exports: any;
}

declare module 'react-is/umd/react-is.development' {
  declare module.exports: any;
}

declare module 'react-is/umd/react-is.production.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-is/cjs/react-is.development.js' {
  declare module.exports: $Exports<'react-is/cjs/react-is.development'>;
}
declare module 'react-is/cjs/react-is.production.min.js' {
  declare module.exports: $Exports<'react-is/cjs/react-is.production.min'>;
}
declare module 'react-is/index' {
  declare module.exports: $Exports<'react-is'>;
}
declare module 'react-is/index.js' {
  declare module.exports: $Exports<'react-is'>;
}
declare module 'react-is/umd/react-is.development.js' {
  declare module.exports: $Exports<'react-is/umd/react-is.development'>;
}
declare module 'react-is/umd/react-is.production.min.js' {
  declare module.exports: $Exports<'react-is/umd/react-is.production.min'>;
}
