// flow-typed signature: 0533cf4c3dd8abb74d7bfc21895ecbf1
// flow-typed version: <<STUB>>/react-frame-component_v^4.0.2/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-frame-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-frame-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-frame-component/dist/appbundle' {
  declare module.exports: any;
}

declare module 'react-frame-component/lib/Content' {
  declare module.exports: any;
}

declare module 'react-frame-component/lib/Context' {
  declare module.exports: any;
}

declare module 'react-frame-component/lib/Frame' {
  declare module.exports: any;
}

declare module 'react-frame-component/lib/index' {
  declare module.exports: any;
}

declare module 'react-frame-component/src/Content' {
  declare module.exports: any;
}

declare module 'react-frame-component/src/Context' {
  declare module.exports: any;
}

declare module 'react-frame-component/src/Frame' {
  declare module.exports: any;
}

declare module 'react-frame-component/src/index' {
  declare module.exports: any;
}

declare module 'react-frame-component/test/Content.spec' {
  declare module.exports: any;
}

declare module 'react-frame-component/test/Context.spec' {
  declare module.exports: any;
}

declare module 'react-frame-component/test/Frame.spec' {
  declare module.exports: any;
}

declare module 'react-frame-component/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-frame-component/dist/appbundle.js' {
  declare module.exports: $Exports<'react-frame-component/dist/appbundle'>;
}
declare module 'react-frame-component/lib/Content.js' {
  declare module.exports: $Exports<'react-frame-component/lib/Content'>;
}
declare module 'react-frame-component/lib/Context.js' {
  declare module.exports: $Exports<'react-frame-component/lib/Context'>;
}
declare module 'react-frame-component/lib/Frame.js' {
  declare module.exports: $Exports<'react-frame-component/lib/Frame'>;
}
declare module 'react-frame-component/lib/index.js' {
  declare module.exports: $Exports<'react-frame-component/lib/index'>;
}
declare module 'react-frame-component/src/Content.jsx' {
  declare module.exports: $Exports<'react-frame-component/src/Content'>;
}
declare module 'react-frame-component/src/Context.jsx' {
  declare module.exports: $Exports<'react-frame-component/src/Context'>;
}
declare module 'react-frame-component/src/Frame.jsx' {
  declare module.exports: $Exports<'react-frame-component/src/Frame'>;
}
declare module 'react-frame-component/src/index.js' {
  declare module.exports: $Exports<'react-frame-component/src/index'>;
}
declare module 'react-frame-component/test/Content.spec.jsx' {
  declare module.exports: $Exports<'react-frame-component/test/Content.spec'>;
}
declare module 'react-frame-component/test/Context.spec.jsx' {
  declare module.exports: $Exports<'react-frame-component/test/Context.spec'>;
}
declare module 'react-frame-component/test/Frame.spec.jsx' {
  declare module.exports: $Exports<'react-frame-component/test/Frame.spec'>;
}
declare module 'react-frame-component/webpack.config.js' {
  declare module.exports: $Exports<'react-frame-component/webpack.config'>;
}
