// flow-typed signature: fc47b5b498bacd2f952c0ab124bdfaa2
// flow-typed version: <<STUB>>/rollup_v^1.13.1/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup/dist/rollup.browser.es' {
  declare module.exports: any;
}

declare module 'rollup/dist/rollup.browser' {
  declare module.exports: any;
}

declare module 'rollup/dist/rollup.es' {
  declare module.exports: any;
}

declare module 'rollup/dist/rollup' {
  declare module.exports: any;
}

declare module 'rollup/dist/shared' {
  declare module.exports: any;
}

declare module 'rollup/dist/shared/node-entry' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup/dist/rollup.browser.es.js' {
  declare module.exports: $Exports<'rollup/dist/rollup.browser.es'>;
}
declare module 'rollup/dist/rollup.browser.js' {
  declare module.exports: $Exports<'rollup/dist/rollup.browser'>;
}
declare module 'rollup/dist/rollup.es.js' {
  declare module.exports: $Exports<'rollup/dist/rollup.es'>;
}
declare module 'rollup/dist/rollup.js' {
  declare module.exports: $Exports<'rollup/dist/rollup'>;
}
declare module 'rollup/dist/shared/index' {
  declare module.exports: $Exports<'rollup/dist/shared'>;
}
declare module 'rollup/dist/shared/index.js' {
  declare module.exports: $Exports<'rollup/dist/shared'>;
}
declare module 'rollup/dist/shared/node-entry.js' {
  declare module.exports: $Exports<'rollup/dist/shared/node-entry'>;
}
