// flow-typed signature: e302c5faf706cf8513d84378a47dd501
// flow-typed version: <<STUB>>/rollup-plugin-inject_v^2.0.0/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-inject'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-inject' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-inject/dist/rollup-plugin-inject.cjs' {
  declare module.exports: any;
}

declare module 'rollup-plugin-inject/dist/rollup-plugin-inject.es6' {
  declare module.exports: any;
}

declare module 'rollup-plugin-inject/src/index' {
  declare module.exports: any;
}

declare module 'rollup-plugin-inject/src/makeLegalIdentifier' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-inject/dist/rollup-plugin-inject.cjs.js' {
  declare module.exports: $Exports<'rollup-plugin-inject/dist/rollup-plugin-inject.cjs'>;
}
declare module 'rollup-plugin-inject/dist/rollup-plugin-inject.es6.js' {
  declare module.exports: $Exports<'rollup-plugin-inject/dist/rollup-plugin-inject.es6'>;
}
declare module 'rollup-plugin-inject/src/index.js' {
  declare module.exports: $Exports<'rollup-plugin-inject/src/index'>;
}
declare module 'rollup-plugin-inject/src/makeLegalIdentifier.js' {
  declare module.exports: $Exports<'rollup-plugin-inject/src/makeLegalIdentifier'>;
}
