// flow-typed signature: 1249fcc132e0f2771400650288071ae0
// flow-typed version: <<STUB>>/rollup-plugin-flow_v^1.1.1/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'rollup-plugin-flow/index' {
  declare module.exports: $Exports<'rollup-plugin-flow'>;
}
declare module 'rollup-plugin-flow/index.js' {
  declare module.exports: $Exports<'rollup-plugin-flow'>;
}
