// flow-typed signature: 29b9bec6fa0ce23d2b65864be84096de
// flow-typed version: <<STUB>>/rollup-plugin-babel_v^2.6.1/flow_v0.32.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-babel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-babel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-babel/dist/rollup-plugin-babel.cjs' {
  declare module.exports: any;
}

declare module 'rollup-plugin-babel/dist/rollup-plugin-babel.es6' {
  declare module.exports: any;
}

declare module 'rollup-plugin-babel/src/constants' {
  declare module.exports: any;
}

declare module 'rollup-plugin-babel/src/index' {
  declare module.exports: any;
}

declare module 'rollup-plugin-babel/src/preflightCheck' {
  declare module.exports: any;
}

declare module 'rollup-plugin-babel/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js' {
  declare module.exports: $Exports<'rollup-plugin-babel/dist/rollup-plugin-babel.cjs'>;
}
declare module 'rollup-plugin-babel/dist/rollup-plugin-babel.es6.js' {
  declare module.exports: $Exports<'rollup-plugin-babel/dist/rollup-plugin-babel.es6'>;
}
declare module 'rollup-plugin-babel/src/constants.js' {
  declare module.exports: $Exports<'rollup-plugin-babel/src/constants'>;
}
declare module 'rollup-plugin-babel/src/index.js' {
  declare module.exports: $Exports<'rollup-plugin-babel/src/index'>;
}
declare module 'rollup-plugin-babel/src/preflightCheck.js' {
  declare module.exports: $Exports<'rollup-plugin-babel/src/preflightCheck'>;
}
declare module 'rollup-plugin-babel/src/utils.js' {
  declare module.exports: $Exports<'rollup-plugin-babel/src/utils'>;
}
