// flow-typed signature: 25a657cfecad14b46a99412c79f7d57d
// flow-typed version: <<STUB>>/stylis-rule-sheet_v^0.0.10/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylis-rule-sheet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylis-rule-sheet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'stylis-rule-sheet/index' {
  declare module.exports: $Exports<'stylis-rule-sheet'>;
}
declare module 'stylis-rule-sheet/index.js' {
  declare module.exports: $Exports<'stylis-rule-sheet'>;
}
