// flow-typed signature: c2f55640f21684671437622668c77ece
// flow-typed version: <<STUB>>/stylis-rtl_v^1.0.1/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylis-rtl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylis-rtl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylis-rtl/dist/stylis-rtl' {
  declare module.exports: any;
}

declare module 'stylis-rtl/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'stylis-rtl/flow-typed/npm/jest_v23.x.x' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylis-rtl/dist/stylis-rtl.js' {
  declare module.exports: $Exports<'stylis-rtl/dist/stylis-rtl'>;
}
declare module 'stylis-rtl/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'stylis-rtl/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'stylis-rtl/flow-typed/npm/jest_v23.x.x.js' {
  declare module.exports: $Exports<'stylis-rtl/flow-typed/npm/jest_v23.x.x'>;
}
