// flow-typed signature: a03f8da2c14979e1fd547f310e373abb
// flow-typed version: <<STUB>>/supports-color_v^5.5.0/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'supports-color'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'supports-color' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'supports-color/browser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'supports-color/browser.js' {
  declare module.exports: $Exports<'supports-color/browser'>;
}
declare module 'supports-color/index' {
  declare module.exports: $Exports<'supports-color'>;
}
declare module 'supports-color/index.js' {
  declare module.exports: $Exports<'supports-color'>;
}
