// flow-typed signature: 4a0354899904bbf4240a6420cf88571c
// flow-typed version: <<STUB>>/tiny-invariant_v6.1.1/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tiny-invariant'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tiny-invariant' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tiny-invariant/dist/tiny-invariant.cjs' {
  declare module.exports: any;
}

declare module 'tiny-invariant/dist/tiny-invariant.esm' {
  declare module.exports: any;
}

declare module 'tiny-invariant/dist/tiny-invariant' {
  declare module.exports: any;
}

declare module 'tiny-invariant/dist/tiny-invariant.min' {
  declare module.exports: any;
}

declare module 'tiny-invariant/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tiny-invariant/dist/tiny-invariant.cjs.js' {
  declare module.exports: $Exports<'tiny-invariant/dist/tiny-invariant.cjs'>;
}
declare module 'tiny-invariant/dist/tiny-invariant.esm.js' {
  declare module.exports: $Exports<'tiny-invariant/dist/tiny-invariant.esm'>;
}
declare module 'tiny-invariant/dist/tiny-invariant.js' {
  declare module.exports: $Exports<'tiny-invariant/dist/tiny-invariant'>;
}
declare module 'tiny-invariant/dist/tiny-invariant.min.js' {
  declare module.exports: $Exports<'tiny-invariant/dist/tiny-invariant.min'>;
}
declare module 'tiny-invariant/src/index.js' {
  declare module.exports: $Exports<'tiny-invariant/src/index'>;
}
