// flow-typed signature: 74648cddcffc7b8bf929558fe93e484a
// flow-typed version: <<STUB>>/wsrun_v^5.0.2/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wsrun'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wsrun' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wsrun/bin/wsrun' {
  declare module.exports: any;
}

declare module 'wsrun/build/cmd-process' {
  declare module.exports: any;
}

declare module 'wsrun/build/console' {
  declare module.exports: any;
}

declare module 'wsrun/build/console.spec' {
  declare module.exports: any;
}

declare module 'wsrun/build/enums' {
  declare module.exports: any;
}

declare module 'wsrun/build/filter-changed-packages' {
  declare module.exports: any;
}

declare module 'wsrun/build/filter-changed-packages.spec' {
  declare module.exports: any;
}

declare module 'wsrun/build/fix-paths' {
  declare module.exports: any;
}

declare module 'wsrun/build/fix-paths.spec' {
  declare module.exports: any;
}

declare module 'wsrun/build' {
  declare module.exports: any;
}

declare module 'wsrun/build/rev-deps' {
  declare module.exports: any;
}

declare module 'wsrun/build/rev-deps.spec' {
  declare module.exports: any;
}

declare module 'wsrun/build/run-graph' {
  declare module.exports: any;
}

declare module 'wsrun/build/utils' {
  declare module.exports: any;
}

declare module 'wsrun/build/workspace' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wsrun/bin/wsrun.js' {
  declare module.exports: $Exports<'wsrun/bin/wsrun'>;
}
declare module 'wsrun/build/cmd-process.js' {
  declare module.exports: $Exports<'wsrun/build/cmd-process'>;
}
declare module 'wsrun/build/console.js' {
  declare module.exports: $Exports<'wsrun/build/console'>;
}
declare module 'wsrun/build/console.spec.js' {
  declare module.exports: $Exports<'wsrun/build/console.spec'>;
}
declare module 'wsrun/build/enums.js' {
  declare module.exports: $Exports<'wsrun/build/enums'>;
}
declare module 'wsrun/build/filter-changed-packages.js' {
  declare module.exports: $Exports<'wsrun/build/filter-changed-packages'>;
}
declare module 'wsrun/build/filter-changed-packages.spec.js' {
  declare module.exports: $Exports<'wsrun/build/filter-changed-packages.spec'>;
}
declare module 'wsrun/build/fix-paths.js' {
  declare module.exports: $Exports<'wsrun/build/fix-paths'>;
}
declare module 'wsrun/build/fix-paths.spec.js' {
  declare module.exports: $Exports<'wsrun/build/fix-paths.spec'>;
}
declare module 'wsrun/build/index' {
  declare module.exports: $Exports<'wsrun/build'>;
}
declare module 'wsrun/build/index.js' {
  declare module.exports: $Exports<'wsrun/build'>;
}
declare module 'wsrun/build/rev-deps.js' {
  declare module.exports: $Exports<'wsrun/build/rev-deps'>;
}
declare module 'wsrun/build/rev-deps.spec.js' {
  declare module.exports: $Exports<'wsrun/build/rev-deps.spec'>;
}
declare module 'wsrun/build/run-graph.js' {
  declare module.exports: $Exports<'wsrun/build/run-graph'>;
}
declare module 'wsrun/build/utils.js' {
  declare module.exports: $Exports<'wsrun/build/utils'>;
}
declare module 'wsrun/build/workspace.js' {
  declare module.exports: $Exports<'wsrun/build/workspace'>;
}
