// flow-typed signature: e90c56bb3b0d5cccd406b0b1924ab93c
// flow-typed version: <<STUB>>/wsrun_v^3.6.4/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wsrun'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wsrun' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wsrun/build/cmd-process' {
  declare module.exports: any;
}

declare module 'wsrun/build/enums' {
  declare module.exports: any;
}

declare module 'wsrun/build/fix-paths' {
  declare module.exports: any;
}

declare module 'wsrun/build/fix-paths.spec' {
  declare module.exports: any;
}

declare module 'wsrun/build/index' {
  declare module.exports: any;
}

declare module 'wsrun/build/run-graph' {
  declare module.exports: any;
}

declare module 'wsrun/build/utils' {
  declare module.exports: any;
}

declare module 'wsrun/build/workspace' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wsrun/build/cmd-process.js' {
  declare module.exports: $Exports<'wsrun/build/cmd-process'>;
}
declare module 'wsrun/build/enums.js' {
  declare module.exports: $Exports<'wsrun/build/enums'>;
}
declare module 'wsrun/build/fix-paths.js' {
  declare module.exports: $Exports<'wsrun/build/fix-paths'>;
}
declare module 'wsrun/build/fix-paths.spec.js' {
  declare module.exports: $Exports<'wsrun/build/fix-paths.spec'>;
}
declare module 'wsrun/build/index.js' {
  declare module.exports: $Exports<'wsrun/build/index'>;
}
declare module 'wsrun/build/run-graph.js' {
  declare module.exports: $Exports<'wsrun/build/run-graph'>;
}
declare module 'wsrun/build/utils.js' {
  declare module.exports: $Exports<'wsrun/build/utils'>;
}
declare module 'wsrun/build/workspace.js' {
  declare module.exports: $Exports<'wsrun/build/workspace'>;
}
