// flow-typed signature: 31eb46abbb940d1871cad5b72e2d5a1e
// flow-typed version: <<STUB>>/@babel/helper-module-imports_v^7.0.0/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/helper-module-imports'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/helper-module-imports' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/helper-module-imports/lib/import-builder' {
  declare module.exports: any;
}

declare module '@babel/helper-module-imports/lib/import-injector' {
  declare module.exports: any;
}

declare module '@babel/helper-module-imports/lib/index' {
  declare module.exports: any;
}

declare module '@babel/helper-module-imports/lib/is-module' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/helper-module-imports/lib/import-builder.js' {
  declare module.exports: $Exports<'@babel/helper-module-imports/lib/import-builder'>;
}
declare module '@babel/helper-module-imports/lib/import-injector.js' {
  declare module.exports: $Exports<'@babel/helper-module-imports/lib/import-injector'>;
}
declare module '@babel/helper-module-imports/lib/index.js' {
  declare module.exports: $Exports<'@babel/helper-module-imports/lib/index'>;
}
declare module '@babel/helper-module-imports/lib/is-module.js' {
  declare module.exports: $Exports<'@babel/helper-module-imports/lib/is-module'>;
}
