// flow-typed signature: ba3839893686e751c31cbf411aa42ce6
// flow-typed version: <<STUB>>/@babel/preset-env_v^7.0.0/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/preset-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/preset-env' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/preset-env/data/built-ins.json' {
  declare module.exports: any;
}

declare module '@babel/preset-env/data/corejs2-built-in-features' {
  declare module.exports: any;
}

declare module '@babel/preset-env/data/plugin-features' {
  declare module.exports: any;
}

declare module '@babel/preset-env/data/shipped-proposals' {
  declare module.exports: any;
}

declare module '@babel/preset-env/data/unreleased-labels' {
  declare module.exports: any;
}

declare module '@babel/preset-env/lib/available-plugins' {
  declare module.exports: any;
}

declare module '@babel/preset-env/lib/debug' {
  declare module.exports: any;
}

declare module '@babel/preset-env/lib/filter-items' {
  declare module.exports: any;
}

declare module '@babel/preset-env/lib/get-option-specific-excludes' {
  declare module.exports: any;
}

declare module '@babel/preset-env/lib/index' {
  declare module.exports: any;
}

declare module '@babel/preset-env/lib/module-transformations' {
  declare module.exports: any;
}

declare module '@babel/preset-env/lib/normalize-options' {
  declare module.exports: any;
}

declare module '@babel/preset-env/lib/options' {
  declare module.exports: any;
}

declare module '@babel/preset-env/lib/polyfills/corejs2/built-in-definitions' {
  declare module.exports: any;
}

declare module '@babel/preset-env/lib/polyfills/corejs2/entry-plugin' {
  declare module.exports: any;
}

declare module '@babel/preset-env/lib/polyfills/corejs2/get-platform-specific-default' {
  declare module.exports: any;
}

declare module '@babel/preset-env/lib/polyfills/corejs2/usage-plugin' {
  declare module.exports: any;
}

declare module '@babel/preset-env/lib/polyfills/corejs3/built-in-definitions' {
  declare module.exports: any;
}

declare module '@babel/preset-env/lib/polyfills/corejs3/entry-plugin' {
  declare module.exports: any;
}

declare module '@babel/preset-env/lib/polyfills/corejs3/shipped-proposals' {
  declare module.exports: any;
}

declare module '@babel/preset-env/lib/polyfills/corejs3/usage-plugin' {
  declare module.exports: any;
}

declare module '@babel/preset-env/lib/polyfills/regenerator/entry-plugin' {
  declare module.exports: any;
}

declare module '@babel/preset-env/lib/polyfills/regenerator/usage-plugin' {
  declare module.exports: any;
}

declare module '@babel/preset-env/lib/targets-parser' {
  declare module.exports: any;
}

declare module '@babel/preset-env/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/preset-env/data/built-ins.json.js' {
  declare module.exports: $Exports<'@babel/preset-env/data/built-ins.json'>;
}
declare module '@babel/preset-env/data/corejs2-built-in-features.js' {
  declare module.exports: $Exports<'@babel/preset-env/data/corejs2-built-in-features'>;
}
declare module '@babel/preset-env/data/plugin-features.js' {
  declare module.exports: $Exports<'@babel/preset-env/data/plugin-features'>;
}
declare module '@babel/preset-env/data/shipped-proposals.js' {
  declare module.exports: $Exports<'@babel/preset-env/data/shipped-proposals'>;
}
declare module '@babel/preset-env/data/unreleased-labels.js' {
  declare module.exports: $Exports<'@babel/preset-env/data/unreleased-labels'>;
}
declare module '@babel/preset-env/lib/available-plugins.js' {
  declare module.exports: $Exports<'@babel/preset-env/lib/available-plugins'>;
}
declare module '@babel/preset-env/lib/debug.js' {
  declare module.exports: $Exports<'@babel/preset-env/lib/debug'>;
}
declare module '@babel/preset-env/lib/filter-items.js' {
  declare module.exports: $Exports<'@babel/preset-env/lib/filter-items'>;
}
declare module '@babel/preset-env/lib/get-option-specific-excludes.js' {
  declare module.exports: $Exports<'@babel/preset-env/lib/get-option-specific-excludes'>;
}
declare module '@babel/preset-env/lib/index.js' {
  declare module.exports: $Exports<'@babel/preset-env/lib/index'>;
}
declare module '@babel/preset-env/lib/module-transformations.js' {
  declare module.exports: $Exports<'@babel/preset-env/lib/module-transformations'>;
}
declare module '@babel/preset-env/lib/normalize-options.js' {
  declare module.exports: $Exports<'@babel/preset-env/lib/normalize-options'>;
}
declare module '@babel/preset-env/lib/options.js' {
  declare module.exports: $Exports<'@babel/preset-env/lib/options'>;
}
declare module '@babel/preset-env/lib/polyfills/corejs2/built-in-definitions.js' {
  declare module.exports: $Exports<'@babel/preset-env/lib/polyfills/corejs2/built-in-definitions'>;
}
declare module '@babel/preset-env/lib/polyfills/corejs2/entry-plugin.js' {
  declare module.exports: $Exports<'@babel/preset-env/lib/polyfills/corejs2/entry-plugin'>;
}
declare module '@babel/preset-env/lib/polyfills/corejs2/get-platform-specific-default.js' {
  declare module.exports: $Exports<'@babel/preset-env/lib/polyfills/corejs2/get-platform-specific-default'>;
}
declare module '@babel/preset-env/lib/polyfills/corejs2/usage-plugin.js' {
  declare module.exports: $Exports<'@babel/preset-env/lib/polyfills/corejs2/usage-plugin'>;
}
declare module '@babel/preset-env/lib/polyfills/corejs3/built-in-definitions.js' {
  declare module.exports: $Exports<'@babel/preset-env/lib/polyfills/corejs3/built-in-definitions'>;
}
declare module '@babel/preset-env/lib/polyfills/corejs3/entry-plugin.js' {
  declare module.exports: $Exports<'@babel/preset-env/lib/polyfills/corejs3/entry-plugin'>;
}
declare module '@babel/preset-env/lib/polyfills/corejs3/shipped-proposals.js' {
  declare module.exports: $Exports<'@babel/preset-env/lib/polyfills/corejs3/shipped-proposals'>;
}
declare module '@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js' {
  declare module.exports: $Exports<'@babel/preset-env/lib/polyfills/corejs3/usage-plugin'>;
}
declare module '@babel/preset-env/lib/polyfills/regenerator/entry-plugin.js' {
  declare module.exports: $Exports<'@babel/preset-env/lib/polyfills/regenerator/entry-plugin'>;
}
declare module '@babel/preset-env/lib/polyfills/regenerator/usage-plugin.js' {
  declare module.exports: $Exports<'@babel/preset-env/lib/polyfills/regenerator/usage-plugin'>;
}
declare module '@babel/preset-env/lib/targets-parser.js' {
  declare module.exports: $Exports<'@babel/preset-env/lib/targets-parser'>;
}
declare module '@babel/preset-env/lib/utils.js' {
  declare module.exports: $Exports<'@babel/preset-env/lib/utils'>;
}
