// flow-typed signature: a16b5dc5fe60f389e8f81b6e5d3fe175
// flow-typed version: <<STUB>>/buffer_v^5.0.2/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'buffer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'buffer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'buffer/test/base64' {
  declare module.exports: any;
}

declare module 'buffer/test/basic' {
  declare module.exports: any;
}

declare module 'buffer/test/compare' {
  declare module.exports: any;
}

declare module 'buffer/test/constructor' {
  declare module.exports: any;
}

declare module 'buffer/test/from-string' {
  declare module.exports: any;
}

declare module 'buffer/test/is-buffer' {
  declare module.exports: any;
}

declare module 'buffer/test/methods' {
  declare module.exports: any;
}

declare module 'buffer/test/node/test-buffer-alloc' {
  declare module.exports: any;
}

declare module 'buffer/test/node/test-buffer-arraybuffer' {
  declare module.exports: any;
}

declare module 'buffer/test/node/test-buffer-ascii' {
  declare module.exports: any;
}

declare module 'buffer/test/node/test-buffer-bad-overload' {
  declare module.exports: any;
}

declare module 'buffer/test/node/test-buffer-badhex' {
  declare module.exports: any;
}

declare module 'buffer/test/node/test-buffer-bytelength' {
  declare module.exports: any;
}

declare module 'buffer/test/node/test-buffer-compare-offset' {
  declare module.exports: any;
}

declare module 'buffer/test/node/test-buffer-concat' {
  declare module.exports: any;
}

declare module 'buffer/test/node/test-buffer-fill' {
  declare module.exports: any;
}

declare module 'buffer/test/node/test-buffer-includes' {
  declare module.exports: any;
}

declare module 'buffer/test/node/test-buffer-indexof' {
  declare module.exports: any;
}

declare module 'buffer/test/node/test-buffer-inheritance' {
  declare module.exports: any;
}

declare module 'buffer/test/node/test-buffer-inspect' {
  declare module.exports: any;
}

declare module 'buffer/test/node/test-buffer-iterator' {
  declare module.exports: any;
}

declare module 'buffer/test/node/test-buffer-safe-unsafe' {
  declare module.exports: any;
}

declare module 'buffer/test/node/test-buffer-slow' {
  declare module.exports: any;
}

declare module 'buffer/test/node/test-buffer-swap' {
  declare module.exports: any;
}

declare module 'buffer/test/node/test-buffer-zero-fill-cli' {
  declare module.exports: any;
}

declare module 'buffer/test/node/test-buffer-zero-fill-reset' {
  declare module.exports: any;
}

declare module 'buffer/test/node/test-buffer' {
  declare module.exports: any;
}

declare module 'buffer/test/slice' {
  declare module.exports: any;
}

declare module 'buffer/test/static' {
  declare module.exports: any;
}

declare module 'buffer/test/to-string' {
  declare module.exports: any;
}

declare module 'buffer/test/write_infinity' {
  declare module.exports: any;
}

declare module 'buffer/test/write' {
  declare module.exports: any;
}

// Filename aliases
declare module 'buffer/index' {
  declare module.exports: $Exports<'buffer'>;
}
declare module 'buffer/index.js' {
  declare module.exports: $Exports<'buffer'>;
}
declare module 'buffer/test/base64.js' {
  declare module.exports: $Exports<'buffer/test/base64'>;
}
declare module 'buffer/test/basic.js' {
  declare module.exports: $Exports<'buffer/test/basic'>;
}
declare module 'buffer/test/compare.js' {
  declare module.exports: $Exports<'buffer/test/compare'>;
}
declare module 'buffer/test/constructor.js' {
  declare module.exports: $Exports<'buffer/test/constructor'>;
}
declare module 'buffer/test/from-string.js' {
  declare module.exports: $Exports<'buffer/test/from-string'>;
}
declare module 'buffer/test/is-buffer.js' {
  declare module.exports: $Exports<'buffer/test/is-buffer'>;
}
declare module 'buffer/test/methods.js' {
  declare module.exports: $Exports<'buffer/test/methods'>;
}
declare module 'buffer/test/node/test-buffer-alloc.js' {
  declare module.exports: $Exports<'buffer/test/node/test-buffer-alloc'>;
}
declare module 'buffer/test/node/test-buffer-arraybuffer.js' {
  declare module.exports: $Exports<'buffer/test/node/test-buffer-arraybuffer'>;
}
declare module 'buffer/test/node/test-buffer-ascii.js' {
  declare module.exports: $Exports<'buffer/test/node/test-buffer-ascii'>;
}
declare module 'buffer/test/node/test-buffer-bad-overload.js' {
  declare module.exports: $Exports<'buffer/test/node/test-buffer-bad-overload'>;
}
declare module 'buffer/test/node/test-buffer-badhex.js' {
  declare module.exports: $Exports<'buffer/test/node/test-buffer-badhex'>;
}
declare module 'buffer/test/node/test-buffer-bytelength.js' {
  declare module.exports: $Exports<'buffer/test/node/test-buffer-bytelength'>;
}
declare module 'buffer/test/node/test-buffer-compare-offset.js' {
  declare module.exports: $Exports<'buffer/test/node/test-buffer-compare-offset'>;
}
declare module 'buffer/test/node/test-buffer-concat.js' {
  declare module.exports: $Exports<'buffer/test/node/test-buffer-concat'>;
}
declare module 'buffer/test/node/test-buffer-fill.js' {
  declare module.exports: $Exports<'buffer/test/node/test-buffer-fill'>;
}
declare module 'buffer/test/node/test-buffer-includes.js' {
  declare module.exports: $Exports<'buffer/test/node/test-buffer-includes'>;
}
declare module 'buffer/test/node/test-buffer-indexof.js' {
  declare module.exports: $Exports<'buffer/test/node/test-buffer-indexof'>;
}
declare module 'buffer/test/node/test-buffer-inheritance.js' {
  declare module.exports: $Exports<'buffer/test/node/test-buffer-inheritance'>;
}
declare module 'buffer/test/node/test-buffer-inspect.js' {
  declare module.exports: $Exports<'buffer/test/node/test-buffer-inspect'>;
}
declare module 'buffer/test/node/test-buffer-iterator.js' {
  declare module.exports: $Exports<'buffer/test/node/test-buffer-iterator'>;
}
declare module 'buffer/test/node/test-buffer-safe-unsafe.js' {
  declare module.exports: $Exports<'buffer/test/node/test-buffer-safe-unsafe'>;
}
declare module 'buffer/test/node/test-buffer-slow.js' {
  declare module.exports: $Exports<'buffer/test/node/test-buffer-slow'>;
}
declare module 'buffer/test/node/test-buffer-swap.js' {
  declare module.exports: $Exports<'buffer/test/node/test-buffer-swap'>;
}
declare module 'buffer/test/node/test-buffer-zero-fill-cli.js' {
  declare module.exports: $Exports<'buffer/test/node/test-buffer-zero-fill-cli'>;
}
declare module 'buffer/test/node/test-buffer-zero-fill-reset.js' {
  declare module.exports: $Exports<'buffer/test/node/test-buffer-zero-fill-reset'>;
}
declare module 'buffer/test/node/test-buffer.js' {
  declare module.exports: $Exports<'buffer/test/node/test-buffer'>;
}
declare module 'buffer/test/slice.js' {
  declare module.exports: $Exports<'buffer/test/slice'>;
}
declare module 'buffer/test/static.js' {
  declare module.exports: $Exports<'buffer/test/static'>;
}
declare module 'buffer/test/to-string.js' {
  declare module.exports: $Exports<'buffer/test/to-string'>;
}
declare module 'buffer/test/write_infinity.js' {
  declare module.exports: $Exports<'buffer/test/write_infinity'>;
}
declare module 'buffer/test/write.js' {
  declare module.exports: $Exports<'buffer/test/write'>;
}
