// flow-typed signature: 3de05e6ca36df049f4530c6bdbf3b83e
// flow-typed version: <<STUB>>/chokidar_v^1.6.1/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chokidar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'chokidar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chokidar/lib/fsevents-handler' {
  declare module.exports: any;
}

declare module 'chokidar/lib/nodefs-handler' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chokidar/index' {
  declare module.exports: $Exports<'chokidar'>;
}
declare module 'chokidar/index.js' {
  declare module.exports: $Exports<'chokidar'>;
}
declare module 'chokidar/lib/fsevents-handler.js' {
  declare module.exports: $Exports<'chokidar/lib/fsevents-handler'>;
}
declare module 'chokidar/lib/nodefs-handler.js' {
  declare module.exports: $Exports<'chokidar/lib/nodefs-handler'>;
}
