// flow-typed signature: f0ef96c7e47bf8cd87980955ec08b419
// flow-typed version: <<STUB>>/jest-image-snapshot_v^2.5.0/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-image-snapshot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-image-snapshot' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-image-snapshot/__tests__/diff-snapshot.spec' {
  declare module.exports: any;
}

declare module 'jest-image-snapshot/__tests__/index.spec' {
  declare module.exports: any;
}

declare module 'jest-image-snapshot/__tests__/integration.spec' {
  declare module.exports: any;
}

declare module 'jest-image-snapshot/examples/__tests__/local-image.spec' {
  declare module.exports: any;
}

declare module 'jest-image-snapshot/examples/__tests__/puppeteer-example.spec' {
  declare module.exports: any;
}

declare module 'jest-image-snapshot/examples/image-reporter' {
  declare module.exports: any;
}

declare module 'jest-image-snapshot/examples/jest-setup' {
  declare module.exports: any;
}

declare module 'jest-image-snapshot/src/diff-process' {
  declare module.exports: any;
}

declare module 'jest-image-snapshot/src/diff-snapshot' {
  declare module.exports: any;
}

declare module 'jest-image-snapshot/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-image-snapshot/__tests__/diff-snapshot.spec.js' {
  declare module.exports: $Exports<'jest-image-snapshot/__tests__/diff-snapshot.spec'>;
}
declare module 'jest-image-snapshot/__tests__/index.spec.js' {
  declare module.exports: $Exports<'jest-image-snapshot/__tests__/index.spec'>;
}
declare module 'jest-image-snapshot/__tests__/integration.spec.js' {
  declare module.exports: $Exports<'jest-image-snapshot/__tests__/integration.spec'>;
}
declare module 'jest-image-snapshot/examples/__tests__/local-image.spec.js' {
  declare module.exports: $Exports<'jest-image-snapshot/examples/__tests__/local-image.spec'>;
}
declare module 'jest-image-snapshot/examples/__tests__/puppeteer-example.spec.js' {
  declare module.exports: $Exports<'jest-image-snapshot/examples/__tests__/puppeteer-example.spec'>;
}
declare module 'jest-image-snapshot/examples/image-reporter.js' {
  declare module.exports: $Exports<'jest-image-snapshot/examples/image-reporter'>;
}
declare module 'jest-image-snapshot/examples/jest-setup.js' {
  declare module.exports: $Exports<'jest-image-snapshot/examples/jest-setup'>;
}
declare module 'jest-image-snapshot/src/diff-process.js' {
  declare module.exports: $Exports<'jest-image-snapshot/src/diff-process'>;
}
declare module 'jest-image-snapshot/src/diff-snapshot.js' {
  declare module.exports: $Exports<'jest-image-snapshot/src/diff-snapshot'>;
}
declare module 'jest-image-snapshot/src/index.js' {
  declare module.exports: $Exports<'jest-image-snapshot/src/index'>;
}
