// flow-typed signature: 11eea34a7a2b0459a19fa7a69f630536
// flow-typed version: <<STUB>>/rollup-plugin-visualizer_v^0.1.5/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-visualizer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-visualizer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-visualizer/lib/pluginmain' {
  declare module.exports: any;
}

declare module 'rollup-plugin-visualizer/plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-visualizer/lib/pluginmain.js' {
  declare module.exports: $Exports<'rollup-plugin-visualizer/lib/pluginmain'>;
}
declare module 'rollup-plugin-visualizer/plugin.js' {
  declare module.exports: $Exports<'rollup-plugin-visualizer/plugin'>;
}
