// flow-typed signature: 35d4eb9da83fea7e08b720bbb15abb46
// flow-typed version: <<STUB>>/stylis_v^3.5.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylis/stylis' {
  declare module.exports: any;
}

declare module 'stylis/stylis.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylis/stylis.js' {
  declare module.exports: $Exports<'stylis/stylis'>;
}
declare module 'stylis/stylis.min.js' {
  declare module.exports: $Exports<'stylis/stylis.min'>;
}
